/**
 * Tiny PDF audit-report helper used by FinOps verification exports.
 * Mirrors the CSV export contract: same headers, same row cells, same filter
 * window — just rendered as a paginated landscape PDF with a title block,
 * filter summary, and auto-paginated table.
 *
 * Loads jspdf + jspdf-autotable dynamically so the chunk only ships when an
 * operator actually clicks "PDF".
 */
import { savePdfWithVault } from '@/lib/pdfVault';

export interface PdfAuditMeta {
  /** Top-of-page heading (e.g. "Field Deposit Verification — Audit Report"). */
  title: string;
  /** Subtitle line (e.g. "Generated by Welile FinOps"). */
  subtitle?: string;
  /** Human-readable filter summary lines printed under the title. */
  filters?: string[];
  /** Footer label printed on every page (left-aligned). */
  footerLabel?: string;
}

export async function downloadAuditPdf(
  filename: string,
  headers: string[],
  rows: (string | number | null | undefined)[][],
  meta: PdfAuditMeta,
) {
  const [{ default: jsPDF }, autoTableMod] = await Promise.all([
    import('jspdf'),
    import('jspdf-autotable'),
  ]);
  const autoTable = (autoTableMod as any).default ?? autoTableMod;

  const doc = new jsPDF({ orientation: 'landscape', unit: 'pt', format: 'a4' });
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const generatedAt = new Date().toISOString().replace('T', ' ').slice(0, 19) + ' UTC';

  // Title block
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(14);
  doc.text(meta.title, 32, 36);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  doc.setTextColor(110);
  let cursorY = 52;
  if (meta.subtitle) {
    doc.text(meta.subtitle, 32, cursorY);
    cursorY += 12;
  }
  doc.text(`Generated: ${generatedAt}`, 32, cursorY);
  cursorY += 12;
  doc.text(`Rows: ${rows.length}`, 32, cursorY);
  cursorY += 14;

  if (meta.filters && meta.filters.length > 0) {
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(9);
    doc.setTextColor(60);
    doc.text('Filters applied', 32, cursorY);
    cursorY += 11;
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(110);
    for (const f of meta.filters) {
      doc.text(`• ${f}`, 36, cursorY);
      cursorY += 11;
    }
    cursorY += 4;
  }

  // Render the table — jspdf-autotable handles pagination, column sizing, and
  // header repetition on every page.
  autoTable(doc, {
    startY: cursorY,
    head: [headers],
    body: rows.map((r) => r.map((c) => (c === null || c === undefined ? '' : String(c)))),
    styles: { fontSize: 7, cellPadding: 3, overflow: 'linebreak', valign: 'top' },
    headStyles: { fillColor: [146, 52, 234], textColor: 255, fontStyle: 'bold', fontSize: 7 },
    alternateRowStyles: { fillColor: [250, 250, 252] },
    margin: { left: 24, right: 24, bottom: 36 },
    didDrawPage: () => {
      const pageNum = (doc as any).internal.getNumberOfPages();
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(8);
      doc.setTextColor(140);
      if (meta.footerLabel) {
        doc.text(meta.footerLabel, 24, pageHeight - 16);
      }
      doc.text(`Page ${pageNum}`, pageWidth - 24, pageHeight - 16, { align: 'right' });
    },
  });

  savePdfWithVault(doc as any, filename, {
    label: meta.title,
    category: 'audit',
  });
}

/** Format an ISO timestamp the same way CSV exports do, for filter summaries. */
export function pdfTimestampLabel(iso: string | null | undefined): string {
  if (!iso) return '—';
  try {
    return new Date(iso).toISOString().replace('T', ' ').slice(0, 19) + ' UTC';
  } catch {
    return '—';
  }
}