/**
 * Tiny PDF audit-report helper used by FinOps verification exports.
 * Mirrors the CSV export contract: same headers, same row cells, same filter
 * window — just rendered as a paginated landscape PDF with a title block,
 * filter summary, and auto-paginated table.
 *
 * Loads jspdf + jspdf-autotable dynamically so the chunk only ships when an
 * operator actually clicks "PDF".
 */
import { savePdfWithVault } from '@/lib/pdfVault';

export interface PdfAuditMeta {
  /** Top-of-page heading (e.g. "Field Deposit Verification — Audit Report"). */
  title: string;
  /** Subtitle line (e.g. "Generated by Welile FinOps"). */
  subtitle?: string;
  /** Human-readable filter summary lines printed under the title. */
  filters?: string[];
  /** Footer label printed on every page (left-aligned). */
  footerLabel?: string;
  /** Optional KPI cards rendered as a grid above the table. */
  kpis?: PdfKpi[];
}

export interface PdfKpi {
  label: string;
  value: string;
  hint?: string;
  /** RGB accent for the card's left rail + value color. Defaults to brand purple. */
  accent?: [number, number, number];
}

export async function downloadAuditPdf(
  filename: string,
  headers: string[],
  rows: (string | number | null | undefined)[][],
  meta: PdfAuditMeta,
) {
  const [{ default: jsPDF }, autoTableMod] = await Promise.all([
    import('jspdf'),
    import('jspdf-autotable'),
  ]);
  const autoTable = (autoTableMod as any).default ?? autoTableMod;

  const doc = new jsPDF({ orientation: 'landscape', unit: 'pt', format: 'a4' });
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const generatedAt = new Date().toISOString().replace('T', ' ').slice(0, 19) + ' UTC';

  // Title block
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(14);
  doc.text(meta.title, 32, 36);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  doc.setTextColor(110);
  let cursorY = 52;
  if (meta.subtitle) {
    doc.text(meta.subtitle, 32, cursorY);
    cursorY += 12;
  }
  doc.text(`Generated: ${generatedAt}`, 32, cursorY);
  cursorY += 12;
  doc.text(`Rows: ${rows.length}`, 32, cursorY);
  cursorY += 14;

  if (meta.filters && meta.filters.length > 0) {
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(9);
    doc.setTextColor(60);
    doc.text('Filters applied', 32, cursorY);
    cursorY += 11;
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(110);
    for (const f of meta.filters) {
      doc.text(`• ${f}`, 36, cursorY);
      cursorY += 11;
    }
    cursorY += 4;
  }

  // KPI card grid (rendered above the table).
  if (meta.kpis && meta.kpis.length > 0) {
    const gutter = 10;
    const marginX = 32;
    const usable = pageWidth - marginX * 2;
    const perRow = Math.min(meta.kpis.length, 4);
    const cardW = (usable - gutter * (perRow - 1)) / perRow;
    const cardH = 56;
    meta.kpis.forEach((k, i) => {
      const row = Math.floor(i / perRow);
      const col = i % perRow;
      const x = marginX + col * (cardW + gutter);
      const y = cursorY + row * (cardH + gutter);
      const accent = k.accent ?? [146, 52, 234];
      // Card background
      doc.setDrawColor(230);
      doc.setFillColor(250, 250, 252);
      doc.roundedRect(x, y, cardW, cardH, 4, 4, 'FD');
      // Left accent rail
      doc.setFillColor(accent[0], accent[1], accent[2]);
      doc.roundedRect(x, y, 3, cardH, 1.5, 1.5, 'F');
      // Label
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(8);
      doc.setTextColor(120);
      doc.text(k.label.toUpperCase(), x + 10, y + 14);
      // Value
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(13);
      doc.setTextColor(accent[0], accent[1], accent[2]);
      doc.text(k.value, x + 10, y + 33);
      // Hint
      if (k.hint) {
        doc.setFont('helvetica', 'normal');
        doc.setFontSize(7.5);
        doc.setTextColor(140);
        doc.text(k.hint, x + 10, y + 47);
      }
    });
    const rows = Math.ceil(meta.kpis.length / perRow);
    cursorY += rows * (cardH + gutter) + 6;
    doc.setTextColor(110);
  }

  // Render the table — jspdf-autotable handles pagination, column sizing, and
  // header repetition on every page.
  autoTable(doc, {
    startY: cursorY,
    head: [headers],
    body: rows.map((r) => r.map((c) => (c === null || c === undefined ? '' : String(c)))),
    styles: { fontSize: 7, cellPadding: 3, overflow: 'linebreak', valign: 'top' },
    headStyles: { fillColor: [146, 52, 234], textColor: 255, fontStyle: 'bold', fontSize: 7 },
    alternateRowStyles: { fillColor: [250, 250, 252] },
    margin: { left: 24, right: 24, bottom: 36 },
    didDrawPage: () => {
      const pageNum = (doc as any).internal.getNumberOfPages();
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(8);
      doc.setTextColor(140);
      if (meta.footerLabel) {
        doc.text(meta.footerLabel, 24, pageHeight - 16);
      }
      doc.text(`Page ${pageNum}`, pageWidth - 24, pageHeight - 16, { align: 'right' });
    },
  });

  savePdfWithVault(doc as any, filename, {
    label: meta.title,
    category: 'audit',
  });
}

/** Format an ISO timestamp the same way CSV exports do, for filter summaries. */
export function pdfTimestampLabel(iso: string | null | undefined): string {
  if (!iso) return '—';
  try {
    return new Date(iso).toISOString().replace('T', ' ').slice(0, 19) + ' UTC';
  } catch {
    return '—';
  }
}