project_id = "wirntoujqoyjobfhyelc"

[functions.wallet-transfer]
verify_jwt = true

[functions.agent-deposit]
verify_jwt = true

[functions.agent-withdrawal]
verify_jwt = true

[functions.approve-rent-request]
verify_jwt = true

[functions.product-purchase]
verify_jwt = true

[functions.vendor-login]
verify_jwt = false

[functions.vendor-mark-receipt]
verify_jwt = false

[functions.approve-loan-application]
verify_jwt = true

[functions.loan-reminders]
verify_jwt = false

[functions.process-monthly-rewards]
verify_jwt = false

[functions.approve-deposit]
verify_jwt = true
