// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp-public
// Bundled from src/lib/mcp-public/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp-public/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp-public/tools/how-welile-works.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^4.4.3";

// src/lib/mcp-public/links.ts
var SIGNUP_BASE = "https://welileapp.com/auth";
var LANDING_BASE = "https://welileapp.com/ai";
var SIGNUP_ROLES = ["tenant", "agent", "landlord", "supporter"];
var UUID_RE = /^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
function buildSignupLinks(opts) {
  const source = (opts?.source ?? "chatgpt").trim() || "chatgpt";
  const params = new URLSearchParams({ signup: "1", signup_source: source });
  if (opts?.role && SIGNUP_ROLES.includes(opts.role)) params.set("role", opts.role);
  const signupUrl = `${SIGNUP_BASE}?${params.toString()}`;
  let referralUrl = null;
  const ref = (opts?.referralCode ?? "").trim();
  if (ref && UUID_RE.test(ref)) {
    const refParams = new URLSearchParams(params);
    refParams.set("ref", ref.toLowerCase());
    referralUrl = `${SIGNUP_BASE}?${refParams.toString()}`;
  }
  const landingParams = new URLSearchParams({ signup_source: source });
  if (opts?.role && SIGNUP_ROLES.includes(opts.role)) landingParams.set("role", opts.role);
  if (ref && UUID_RE.test(ref)) landingParams.set("ref", ref.toLowerCase());
  const landingUrl = `${LANDING_BASE}?${landingParams.toString()}`;
  return { signupUrl, referralUrl, landingUrl };
}

// src/lib/mcp-public/tools/how-welile-works.ts
var GUIDED_PROMPTS = [
  "Check my rent access",
  "See agent commissions",
  "See supporter Returns",
  "Get guaranteed rent as a landlord",
  "Check my Welile Trust Score"
];
var FAQS = [
  {
    q: "What is Welile?",
    a: "Welile is a Ugandan platform that helps tenants access rent through a flexible Rent Plan, backed by community Supporters and served on the ground by field agents. All amounts are in Ugandan Shillings (UGX).",
    tags: ["about", "what", "welile", "overview"]
  },
  {
    q: "How do I get rent help as a tenant?",
    a: "Create a free account, complete verification (your national ID and residence), and an agent or landlord connects you to a Rent Plan. You then repay in small, regular amounts that fit your income.",
    tags: ["tenant", "rent", "help", "how", "repay"]
  },
  {
    q: "How do agents earn on Welile?",
    a: "Agents register tenants, list houses, and collect rent in the field. They earn commission on the collections and placements they make, tracked in a wallet they can withdraw from.",
    tags: ["agent", "earn", "commission", "work", "job"]
  },
  {
    q: "How can I support tenants and earn Returns?",
    a: "Become a Supporter: your funds help tenants access rent, and you earn periodic Returns. Rates and terms are shown in the app when you sign up. (Terminology: Supporter, not lender; Returns, not interest.)",
    tags: ["supporter", "invest", "fund", "returns", "earn"]
  },
  {
    q: "How does a landlord benefit?",
    a: "Landlords list their houses and receive guaranteed, on-time rent instead of chasing tenants each month. Welile handles collection through its agent network.",
    tags: ["landlord", "house", "rent", "guarantee"]
  },
  {
    q: "What is the Welile Trust Score / AI ID?",
    a: "Every user builds a Welile Trust Score \u2014 a reliability identity based on real behaviour like on-time payments and verification. A higher score unlocks better access over time.",
    tags: ["trust", "score", "ai id", "identity", "reliability"]
  },
  {
    q: "Is Welile free to join?",
    a: "Yes, creating an account is free. You only ever deal in UGX, and you can start as a tenant, agent, landlord, or Supporter.",
    tags: ["free", "cost", "join", "signup", "price"]
  },
  {
    q: "How do I check what I personally qualify for?",
    a: "Personal figures \u2014 your rent access, wallet balance, commissions, or Returns \u2014 are shown once you create a free account and sign in. Ask 'check my rent access' or 'see agent commissions' to get started, and I'll share the right signup link.",
    tags: ["check", "qualify", "balance", "personal", "account", "my"]
  },
  {
    q: "Is my money safe and what currency is used?",
    a: "Welile operates strictly in Ugandan Shillings (UGX). Every balance, Rent Plan, commission, and Return is recorded in UGX, and your account activity is tied to your verified identity.",
    tags: ["safe", "security", "currency", "ugx", "money"]
  }
];
var how_welile_works_default = defineTool({
  name: "how_welile_works",
  title: "How Welile works",
  description: "Explain how Welile Receipts works for new users (tenants, agents, landlords, and Supporters) and return the signup link. Optionally personalise with a referral code to return a referral signup link. No sign-in required \u2014 safe for prospective users.",
  inputSchema: {
    topic: z.string().describe(
      "Optional keyword to focus the answer (e.g. 'tenant', 'agent', 'supporter', 'landlord', 'trust score'). Omit to get all FAQs."
    ).optional(),
    referral_code: z.string().describe("Optional referral code (the referrer's Welile user id) to build a referral signup link.").optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ topic, referral_code }) => {
    const term = (topic ?? "").trim().toLowerCase();
    const matched = term ? FAQS.filter(
      (f) => f.q.toLowerCase().includes(term) || f.tags.some((t) => t.includes(term) || term.includes(t))
    ) : FAQS;
    const faqs = matched.length > 0 ? matched : FAQS;
    const { signupUrl, referralUrl, landingUrl } = buildSignupLinks({ referralCode: referral_code });
    const faqText = faqs.map((f) => `Q: ${f.q}
A: ${f.a}`).join("\n\n");
    const promptText = `Try asking:
${GUIDED_PROMPTS.map((p) => `\u2022 ${p}`).join("\n")}`;
    const linkText = referralUrl ? `Start here (guided onboarding): ${landingUrl}
Sign up: ${signupUrl}
Referral signup link: ${referralUrl}` : `Start here (guided onboarding): ${landingUrl}
Sign up: ${signupUrl}`;
    return {
      content: [{ type: "text", text: `${faqText}

---
${promptText}

${linkText}` }],
      structuredContent: {
        faqs: faqs.map(({ q, a }) => ({ question: q, answer: a })),
        guided_prompts: GUIDED_PROMPTS,
        landing_url: landingUrl,
        signup_url: signupUrl,
        referral_url: referralUrl,
        currency: "UGX"
      }
    };
  }
});

// src/lib/mcp-public/tools/explore-welile.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^4.4.3";
var FEATURES = [
  {
    intent: "rent_access",
    prompt: "Check my rent access",
    role: "tenant",
    headline: "Access rent with a flexible Rent Plan",
    explanation: "As a tenant you can get help paying rent through a Rent Plan and repay in small, regular UGX amounts that fit your income. To see the amount you qualify for, you create a free account and complete verification (national ID and residence) \u2014 an agent or landlord then connects you to a Rent Plan.",
    next_step: "Create a free tenant account to check your personal rent access and start a Rent Plan."
  },
  {
    intent: "agent_commissions",
    prompt: "See agent commissions",
    role: "agent",
    headline: "Earn commission as a field agent",
    explanation: "Agents register tenants, list houses, and collect rent in the field. You earn commission in UGX on the collections and placements you make, tracked in a wallet you can withdraw from. Your exact earnings and wallet balance are shown once you sign in.",
    next_step: "Create a free agent account to see your commission wallet and start earning."
  },
  {
    intent: "supporter_returns",
    prompt: "See supporter Returns",
    role: "supporter",
    headline: "Support tenants and earn Returns",
    explanation: "As a Supporter your funds help tenants access rent, and you earn periodic Returns in UGX. Rates and terms are shown in the app when you sign up. (Terminology: Supporter, not lender; Returns, not interest.)",
    next_step: "Create a free Supporter account to view current Returns and start supporting tenants."
  },
  {
    intent: "landlord_payouts",
    prompt: "Get guaranteed rent as a landlord",
    role: "landlord",
    headline: "Guaranteed, on-time rent for landlords",
    explanation: "Landlords list their houses and receive guaranteed, on-time rent in UGX instead of chasing tenants each month. Welile handles collection through its agent network.",
    next_step: "Create a free landlord account to list a house and receive guaranteed rent."
  },
  {
    intent: "trust_score",
    prompt: "Check my Welile Trust Score",
    headline: "Build a Welile Trust Score",
    explanation: "Every user builds a Welile Trust Score \u2014 a reliability identity based on real behaviour like on-time payments and verification. A higher score unlocks better access over time. Your personal score appears once you sign in.",
    next_step: "Create a free account to start building your Welile Trust Score."
  }
];
function matchFeature(intent) {
  const term = (intent ?? "").trim().toLowerCase();
  if (!term) return null;
  return FEATURES.find((f) => f.intent === term) ?? FEATURES.find(
    (f) => f.prompt.toLowerCase().includes(term) || f.headline.toLowerCase().includes(term) || term.includes(f.intent.split("_")[0])
  ) ?? null;
}
var explore_welile_default = defineTool2({
  name: "explore_welile",
  title: "Explore Welile (guided prompts)",
  description: "Answer a prospective user's read-only question about what Welile can do for them (e.g. 'check my rent access', 'see agent commissions', 'supporter Returns', 'landlord payouts', 'Trust Score') and return a role-targeted free signup link so they can act. No sign-in required. Amounts in UGX. If no intent is given, returns the full list of guided prompts to suggest.",
  inputSchema: {
    intent: z2.string().describe(
      "The user's goal. One of: rent_access, agent_commissions, supporter_returns, landlord_payouts, trust_score \u2014 or free text like 'check my rent access'. Omit to list all guided prompts."
    ).optional(),
    referral_code: z2.string().describe("Optional referral code (the referrer's Welile user id) to build a referral signup link.").optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ intent, referral_code }) => {
    const feature = matchFeature(intent);
    if (feature) {
      const { signupUrl: signupUrl2, referralUrl, landingUrl: landingUrl2 } = buildSignupLinks({
        referralCode: referral_code,
        role: feature.role
      });
      const linkText = referralUrl ? `Start here (guided onboarding): ${landingUrl2}
Sign up: ${signupUrl2}
Referral signup link: ${referralUrl}` : `Start here (guided onboarding): ${landingUrl2}
Sign up: ${signupUrl2}`;
      return {
        content: [
          {
            type: "text",
            text: `${feature.headline}

${feature.explanation}

Next step: ${feature.next_step}

${linkText}`
          }
        ],
        structuredContent: {
          intent: feature.intent,
          headline: feature.headline,
          explanation: feature.explanation,
          next_step: feature.next_step,
          role: feature.role ?? null,
          landing_url: landingUrl2,
          signup_url: signupUrl2,
          referral_url: referralUrl,
          currency: "UGX"
        }
      };
    }
    const prompts = FEATURES.map((f) => {
      const { signupUrl: signupUrl2, landingUrl: landingUrl2 } = buildSignupLinks({ referralCode: referral_code, role: f.role });
      return {
        prompt: f.prompt,
        intent: f.intent,
        headline: f.headline,
        role: f.role ?? null,
        landing_url: landingUrl2,
        signup_url: signupUrl2
      };
    });
    const menuText = [
      "Ask about any of these to get started with Welile (UGX):",
      ...prompts.map((p) => `\u2022 ${p.prompt}`)
    ].join("\n");
    const { signupUrl, landingUrl } = buildSignupLinks({ referralCode: referral_code });
    return {
      content: [{ type: "text", text: `${menuText}

Start here (guided onboarding): ${landingUrl}
Or sign up now: ${signupUrl}` }],
      structuredContent: { guided_prompts: prompts, landing_url: landingUrl, signup_url: signupUrl, currency: "UGX" }
    };
  }
});

// src/lib/mcp-public/tools/estimate-rent-access.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z3 } from "npm:zod@^4.4.3";
var MONTHLY_RATE = 0.33;
var DEFAULT_DURATIONS = [30, 60, 90];
var AGENT_COMMISSION_RATE = 0.1;
var MIN_RENT = 1e4;
var MAX_RENT = 5e6;
var MIN_DAYS = 7;
var MAX_DAYS = 120;
function computeRentPlan(rent, days) {
  const accessFee = Math.round(rent * (Math.pow(1 + MONTHLY_RATE, days / 30) - 1));
  const requestFee = rent <= 2e5 ? 1e4 : 2e4;
  const totalRepayment = rent + accessFee + requestFee;
  const dailyRepayment = Math.ceil(totalRepayment / days);
  const agentCommission = Math.min(Math.round(rent * AGENT_COMMISSION_RATE), accessFee);
  const accessFeeNet = accessFee - agentCommission;
  const serviceFee = requestFee;
  return {
    durationDays: days,
    principalRent: rent,
    accessFee,
    accessFeeNet,
    agentCommission,
    serviceFee,
    requestFee,
    totalRepayment,
    dailyRepayment
  };
}
var ugx = (n) => `UGX ${Math.round(n).toLocaleString("en-US")}`;
var estimate_rent_access_default = defineTool3({
  name: "estimate_rent_access",
  title: "Estimate rent access (indicative)",
  description: "Give a prospective tenant an INDICATIVE rent-access ballpark in UGX \u2014 total repayment and daily payment for a given monthly rent \u2014 then return the free tenant signup link. No sign-in required. Amounts are illustrative only, not an approval or guarantee; the actual Rent Plan is set after signup and verification. Provide `rent` (monthly rent in UGX). Optionally provide `duration_days` (7-120) for one plan, otherwise 30/60/90-day options are returned. Optional `referral_code` adds a referral signup link.",
  inputSchema: {
    rent: z3.number().describe("Monthly rent in UGX (e.g. 200000). Ballpark only."),
    duration_days: z3.number().describe("Optional Rent Plan length in days (7-120). Omit to compare 30/60/90-day options.").optional(),
    referral_code: z3.string().describe("Optional referral code (the referrer's Welile user id) to build a referral signup link.").optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ rent, duration_days, referral_code }) => {
    const { signupUrl, referralUrl, landingUrl } = buildSignupLinks({
      referralCode: referral_code,
      role: "tenant"
    });
    const linkText = referralUrl ? `Start here (guided onboarding): ${landingUrl}
Create a free tenant account: ${signupUrl}
Referral signup link: ${referralUrl}` : `Start here (guided onboarding): ${landingUrl}
Create a free tenant account: ${signupUrl}`;
    if (!Number.isFinite(rent) || rent < MIN_RENT || rent > MAX_RENT) {
      const text2 = `Please share a monthly rent between ${ugx(MIN_RENT)} and ${ugx(MAX_RENT)} for an indicative estimate.

${linkText}`;
      return {
        content: [{ type: "text", text: text2 }],
        structuredContent: {
          error: "invalid_rent",
          min_rent: MIN_RENT,
          max_rent: MAX_RENT,
          landing_url: landingUrl,
          signup_url: signupUrl,
          referral_url: referralUrl,
          currency: "UGX"
        }
      };
    }
    const roundedRent = Math.round(rent);
    let durations;
    if (duration_days != null) {
      const d = Math.round(duration_days);
      if (!Number.isFinite(d) || d < MIN_DAYS || d > MAX_DAYS) {
        const text2 = `Rent Plan length must be between ${MIN_DAYS} and ${MAX_DAYS} days. Try 30, 60, or 90 days.

${linkText}`;
        return {
          content: [{ type: "text", text: text2 }],
          structuredContent: {
            error: "invalid_duration",
            min_days: MIN_DAYS,
            max_days: MAX_DAYS,
            landing_url: landingUrl,
            signup_url: signupUrl,
            referral_url: referralUrl,
            currency: "UGX"
          }
        };
      }
      durations = [d];
    } else {
      durations = [...DEFAULT_DURATIONS];
    }
    const plans = durations.map((d) => computeRentPlan(roundedRent, d));
    const planBlocks = plans.map(
      (p) => [
        `${p.durationDays}-day plan \u2014 total ~${ugx(p.totalRepayment)} (about ${ugx(p.dailyRepayment)}/day)`,
        `    \u2022 Rent paid to landlord: ${ugx(p.principalRent)}`,
        `    \u2022 Access fee (financing): ${ugx(p.accessFeeNet)}`,
        `    \u2022 Agent commission: ${ugx(p.agentCommission)}`,
        `    \u2022 Service fee: ${ugx(p.serviceFee)}`
      ].join("\n")
    ).join("\n\n");
    const text = [
      `Indicative Rent Plan for a monthly rent of ${ugx(roundedRent)} (UGX):`,
      "",
      planBlocks,
      "",
      "Line items are illustrative only \u2014 the fee split (service vs access vs agent commission) is shown for transparency and does not change the total. This is not an approval or guarantee. Your actual Rent Plan is confirmed after you create a free account and complete verification (national ID and residence).",
      "",
      linkText
    ].join("\n");
    return {
      content: [{ type: "text", text }],
      structuredContent: {
        rent: roundedRent,
        indicative: true,
        monthly_rate_pct: MONTHLY_RATE * 100,
        plans: plans.map((p) => ({
          duration_days: p.durationDays,
          daily_repayment: p.dailyRepayment,
          total_repayment: p.totalRepayment,
          access_fee: p.accessFee,
          request_fee: p.requestFee,
          breakdown: {
            principal_rent: p.principalRent,
            access_fee: p.accessFeeNet,
            agent_commission: p.agentCommission,
            service_fee: p.serviceFee,
            total: p.totalRepayment
          }
        })),
        breakdown_note: "Line items are illustrative only; the service/access/agent-commission split is for transparency and does not change the total.",
        role: "tenant",
        landing_url: landingUrl,
        signup_url: signupUrl,
        referral_url: referralUrl,
        currency: "UGX"
      }
    };
  }
});

// src/lib/mcp-public/tools/estimate-supporter-returns.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z4 } from "npm:zod@^4.4.3";
var REWARD_RATE = 0.15;
var DEFAULT_DURATIONS2 = [3, 6, 12];
var MIN_AMOUNT = 2e4;
var MAX_AMOUNT = 5e8;
var MIN_MONTHS = 1;
var MAX_MONTHS = 36;
function project(amount, months) {
  const monthlyReward = amount * REWARD_RATE;
  const simpleEarnings = monthlyReward * months;
  const simpleTotal = amount + simpleEarnings;
  let balance = amount;
  for (let m = 1; m <= months; m++) balance += balance * REWARD_RATE;
  const compoundEarnings = balance - amount;
  return {
    durationMonths: months,
    monthlyReward: Math.round(monthlyReward),
    simpleEarnings: Math.round(simpleEarnings),
    simpleTotal: Math.round(simpleTotal),
    compoundEarnings: Math.round(compoundEarnings),
    compoundTotal: Math.round(balance)
  };
}
var ugx2 = (n) => `UGX ${Math.round(n).toLocaleString("en-US")}`;
var estimate_supporter_returns_default = defineTool4({
  name: "estimate_supporter_returns",
  title: "Estimate Supporter Returns (illustrative)",
  description: "Give a prospective Supporter an ILLUSTRATIVE Returns range in UGX for a chosen support amount over time (based on 15% monthly platform rewards), then return the free Supporter signup link. No sign-in required. The range spans simple (rewards paid out) to compounding (rewards reinvested) \u2014 it is an illustration only, not a guarantee; actual rates and terms are shown in the app after signup. Provide `amount` (UGX to support). Optionally provide `duration_months` (1-36) for one horizon, otherwise 3/6/12-month options are returned. Optional `referral_code` adds a referral signup link. (Terminology: Supporter, not lender; Returns, not interest.)",
  inputSchema: {
    amount: z4.number().describe("Amount to support in UGX (e.g. 500000). Illustration only."),
    duration_months: z4.number().describe("Optional horizon in months (1-36). Omit to compare 3/6/12-month options.").optional(),
    referral_code: z4.string().describe("Optional referral code (the referrer's Welile user id) to build a referral signup link.").optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ amount, duration_months, referral_code }) => {
    const { signupUrl, referralUrl, landingUrl } = buildSignupLinks({
      referralCode: referral_code,
      role: "supporter"
    });
    const linkText = referralUrl ? `Start here (guided onboarding): ${landingUrl}
Create a free Supporter account: ${signupUrl}
Referral signup link: ${referralUrl}` : `Start here (guided onboarding): ${landingUrl}
Create a free Supporter account: ${signupUrl}`;
    if (!Number.isFinite(amount) || amount < MIN_AMOUNT || amount > MAX_AMOUNT) {
      const text2 = `Please share a support amount between ${ugx2(MIN_AMOUNT)} and ${ugx2(MAX_AMOUNT)} for an illustrative estimate.

${linkText}`;
      return {
        content: [{ type: "text", text: text2 }],
        structuredContent: {
          error: "invalid_amount",
          min_amount: MIN_AMOUNT,
          max_amount: MAX_AMOUNT,
          signup_url: signupUrl,
          landing_url: landingUrl,
          referral_url: referralUrl,
          currency: "UGX"
        }
      };
    }
    const roundedAmount = Math.round(amount);
    let months;
    if (duration_months != null) {
      const m = Math.round(duration_months);
      if (!Number.isFinite(m) || m < MIN_MONTHS || m > MAX_MONTHS) {
        const text2 = `Horizon must be between ${MIN_MONTHS} and ${MAX_MONTHS} months. Try 3, 6, or 12 months.

${linkText}`;
        return {
          content: [{ type: "text", text: text2 }],
          structuredContent: {
            error: "invalid_duration",
            min_months: MIN_MONTHS,
            max_months: MAX_MONTHS,
            signup_url: signupUrl,
            landing_url: landingUrl,
            referral_url: referralUrl,
            currency: "UGX"
          }
        };
      }
      months = [m];
    } else {
      months = [...DEFAULT_DURATIONS2];
    }
    const projections = months.map((m) => project(roundedAmount, m));
    const lines = projections.map(
      (p) => `\u2022 ${p.durationMonths} month${p.durationMonths === 1 ? "" : "s"}: Returns of ${ugx2(p.simpleEarnings)} (paid out) to ${ugx2(p.compoundEarnings)} (reinvested)`
    ).join("\n");
    const text = [
      `Illustrative Returns for supporting ${ugx2(roundedAmount)} (UGX), at 15% monthly platform rewards:`,
      "",
      lines,
      "",
      "The range spans rewards paid out each month vs. reinvested (compounding). This is an illustration only \u2014 not a guarantee. Actual rates and terms are shown in the app after you create a free account.",
      "",
      linkText
    ].join("\n");
    return {
      content: [{ type: "text", text }],
      structuredContent: {
        amount: roundedAmount,
        illustrative: true,
        monthly_reward_rate_pct: REWARD_RATE * 100,
        projections: projections.map((p) => ({
          duration_months: p.durationMonths,
          monthly_reward: p.monthlyReward,
          simple_earnings: p.simpleEarnings,
          simple_total: p.simpleTotal,
          compound_earnings: p.compoundEarnings,
          compound_total: p.compoundTotal
        })),
        role: "supporter",
        signup_url: signupUrl,
        landing_url: landingUrl,
        referral_url: referralUrl,
        currency: "UGX"
      }
    };
  }
});

// src/lib/mcp-public/tools/find-available-houses.ts
import { createClient } from "npm:@supabase/supabase-js@2.89.0";
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z5 } from "npm:zod@^4.4.3";
var DEFAULT_LIMIT = 5;
var MAX_LIMIT = 10;
function readEnv(name) {
  const g = globalThis;
  return g.Deno?.env?.get(name) ?? g.process?.env?.[name];
}
function anonClient() {
  const url = readEnv("SUPABASE_URL");
  const anonKey = readEnv("SUPABASE_PUBLISHABLE_KEY") ?? readEnv("SUPABASE_ANON_KEY");
  if (!url || !anonKey) throw new Error("Supabase env not configured");
  return createClient(url, anonKey, {
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var ugx3 = (n) => n == null ? "UGX \u2014" : `UGX ${Math.round(n).toLocaleString("en-US")}`;
function amenityList(r) {
  const out = [];
  if (r.has_water) out.push("water");
  if (r.has_electricity) out.push("electricity");
  if (r.has_security) out.push("security");
  if (r.has_parking) out.push("parking");
  if (r.is_furnished) out.push("furnished");
  return out;
}
function locationLabel(r) {
  return [r.village, r.sub_county, r.district, r.region].filter(Boolean).join(", ") || "Location on request";
}
var find_available_houses_default = defineTool5({
  name: "find_available_houses",
  title: "Find available houses",
  description: "Return a small read-only sample of AVAILABLE Welile house listings for a prospective tenant, filtered by district and/or area, then return the free tenant signup link to view details and apply. No sign-in required. Only public, non-sensitive fields are shown (no exact address, GPS, landlord, or contact details). Amounts are in UGX. Provide `district` and/or `area` to narrow the search, optional `max_rent` (UGX) and `limit` (1-10, default 5), and optional `referral_code` for a referral signup link.",
  inputSchema: {
    district: z5.string().describe("Optional district to search (e.g. 'Wakiso', 'Kampala').").optional(),
    area: z5.string().describe("Optional area/neighbourhood \u2014 matches village, sub-county, district, or region.").optional(),
    max_rent: z5.number().describe("Optional maximum monthly rent in UGX.").optional(),
    limit: z5.number().describe("Optional number of listings to return (1-10, default 5).").optional(),
    referral_code: z5.string().describe("Optional referral code (the referrer's Welile user id) to build a referral signup link.").optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ district, area, max_rent, limit, referral_code }) => {
    const { signupUrl, referralUrl, landingUrl } = buildSignupLinks({
      referralCode: referral_code,
      role: "tenant"
    });
    const linkText = referralUrl ? `Start here (guided onboarding): ${landingUrl}
Create a free tenant account to view details and apply: ${signupUrl}
Referral signup link: ${referralUrl}` : `Start here (guided onboarding): ${landingUrl}
Create a free tenant account to view details and apply: ${signupUrl}`;
    const take = Math.min(MAX_LIMIT, Math.max(1, Math.round(limit ?? DEFAULT_LIMIT)));
    let query = anonClient().from("house_listings").select(
      "id,title,house_category,number_of_rooms,monthly_rent,region,district,sub_county,village,has_water,has_electricity,has_security,has_parking,is_furnished,verified,image_urls"
    ).eq("status", "available").not("is_hidden", "is", true);
    const districtTerm = (district ?? "").trim();
    if (districtTerm) query = query.ilike("district", `%${districtTerm}%`);
    const areaTerm = (area ?? "").trim();
    if (areaTerm) {
      const like = `%${areaTerm}%`;
      query = query.or(
        `village.ilike.${like},sub_county.ilike.${like},district.ilike.${like},region.ilike.${like}`
      );
    }
    if (typeof max_rent === "number" && Number.isFinite(max_rent) && max_rent > 0) {
      query = query.lte("monthly_rent", Math.round(max_rent));
    }
    query = query.order("verified", { ascending: false }).order("created_at", { ascending: false }).limit(take);
    const { data, error } = await query;
    if (error) {
      return {
        content: [
          {
            type: "text",
            text: `Sorry, I couldn't fetch listings right now. You can still browse everything after signing up.

${linkText}`
          }
        ],
        isError: true,
        structuredContent: { error: error.message, landing_url: landingUrl, signup_url: signupUrl, referral_url: referralUrl, currency: "UGX" }
      };
    }
    const rows = data ?? [];
    if (rows.length === 0) {
      const where = districtTerm || areaTerm ? ` in "${districtTerm || areaTerm}"` : "";
      return {
        content: [
          {
            type: "text",
            text: `No available listings matched your search${where} right now. New houses are added regularly \u2014 sign up free to save a search and get matched.

${linkText}`
          }
        ],
        structuredContent: {
          count: 0,
          listings: [],
          filters: { district: districtTerm || null, area: areaTerm || null, max_rent: max_rent ?? null },
          role: "tenant",
          signup_url: signupUrl,
          landing_url: landingUrl,
          referral_url: referralUrl,
          currency: "UGX"
        }
      };
    }
    const listings = rows.map((r) => ({
      id: r.id,
      title: r.title ?? "Available house",
      category: r.house_category ?? null,
      rooms: r.number_of_rooms ?? null,
      monthly_rent: r.monthly_rent ?? null,
      location: locationLabel(r),
      district: r.district ?? null,
      amenities: amenityList(r),
      verified: !!r.verified,
      photo_count: Array.isArray(r.image_urls) ? r.image_urls.length : 0
    }));
    const lines = listings.map((l) => {
      const bits = [
        `${ugx3(l.monthly_rent)}/mo`,
        l.rooms ? `${l.rooms} room${l.rooms === 1 ? "" : "s"}` : null,
        l.location,
        l.amenities.length ? l.amenities.join(", ") : null,
        l.verified ? "\u2713 verified" : null
      ].filter(Boolean);
      return `\u2022 ${l.title} \u2014 ${bits.join(" \xB7 ")}`;
    }).join("\n");
    const text = [
      `${listings.length} available house${listings.length === 1 ? "" : "s"} on Welile (UGX):`,
      "",
      lines,
      "",
      "Full details, photos, and contact happen inside the app after you create a free account.",
      "",
      linkText
    ].join("\n");
    return {
      content: [{ type: "text", text }],
      structuredContent: {
        count: listings.length,
        listings,
        filters: { district: districtTerm || null, area: areaTerm || null, max_rent: max_rent ?? null },
        role: "tenant",
        signup_url: signupUrl,
        landing_url: landingUrl,
        referral_url: referralUrl,
        currency: "UGX"
      }
    };
  }
});

// src/lib/mcp-public/index.ts
var mcp_public_default = defineMcp({
  name: "welile-public-mcp",
  title: "Welile Receipts \u2014 Get Started",
  version: "0.1.0",
  instructions: "Public information about Welile Receipts for prospective users \u2014 no account required. Use `how_welile_works` for FAQs and a free signup link. Use `explore_welile` to answer read-only 'what can I do' questions and offer guided prompts such as 'Check my rent access', 'See agent commissions', 'See supporter Returns', 'Get guaranteed rent as a landlord', and 'Check my Welile Trust Score' \u2014 each returns a role-targeted signup link that turns the question into an account. Use `estimate_rent_access` when a prospective tenant gives a monthly rent (UGX) to return an indicative daily/total repayment ballpark plus the free tenant signup link \u2014 the figure is illustrative only, not an approval. Use `estimate_supporter_returns` when a prospective Supporter gives an amount (UGX) to return an illustrative Returns range (simple to compounding, at 15% monthly platform rewards) plus the free Supporter signup link \u2014 an illustration only, not a guarantee. Use `find_available_houses` to return a small read-only sample of available house listings by district/area (public, non-sensitive fields only) plus the free tenant signup link to view details and apply. Personal figures require signing in, so always offer the relevant signup link. All amounts are in UGX.",
  tools: [how_welile_works_default, explore_welile_default, estimate_rent_access_default, estimate_supporter_returns_default, find_available_houses_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_public_default, { functionName: "mcp-public" }));
