// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp-public
// Bundled from src/lib/mcp-public/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp-public/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp-public/tools/how-welile-works.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^4.4.3";
var SIGNUP_BASE = "https://welilereceipts.com/auth";
var UUID_RE = /^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
var FAQS = [
  {
    q: "What is Welile?",
    a: "Welile is a Ugandan platform that helps tenants access rent through a flexible Rent Plan, backed by community Supporters and served on the ground by field agents. All amounts are in Ugandan Shillings (UGX).",
    tags: ["about", "what", "welile", "overview"]
  },
  {
    q: "How do I get rent help as a tenant?",
    a: "Create a free account, complete verification (your national ID and residence), and an agent or landlord connects you to a Rent Plan. You then repay in small, regular amounts that fit your income.",
    tags: ["tenant", "rent", "help", "how", "repay"]
  },
  {
    q: "How do agents earn on Welile?",
    a: "Agents register tenants, list houses, and collect rent in the field. They earn commission on the collections and placements they make, tracked in a wallet they can withdraw from.",
    tags: ["agent", "earn", "commission", "work", "job"]
  },
  {
    q: "How can I support tenants and earn Returns?",
    a: "Become a Supporter: your funds help tenants access rent, and you earn periodic Returns. Rates and terms are shown in the app when you sign up. (Terminology: Supporter, not lender; Returns, not interest.)",
    tags: ["supporter", "invest", "fund", "returns", "earn"]
  },
  {
    q: "How does a landlord benefit?",
    a: "Landlords list their houses and receive guaranteed, on-time rent instead of chasing tenants each month. Welile handles collection through its agent network.",
    tags: ["landlord", "house", "rent", "guarantee"]
  },
  {
    q: "What is the Welile Trust Score / AI ID?",
    a: "Every user builds a Welile Trust Score \u2014 a reliability identity based on real behaviour like on-time payments and verification. A higher score unlocks better access over time.",
    tags: ["trust", "score", "ai id", "identity", "reliability"]
  },
  {
    q: "Is Welile free to join?",
    a: "Yes, creating an account is free. You only ever deal in UGX, and you can start as a tenant, agent, landlord, or Supporter.",
    tags: ["free", "cost", "join", "signup", "price"]
  }
];
function buildLinks(referralCode) {
  const signupUrl = `${SIGNUP_BASE}?signup=1&signup_source=chatgpt`;
  let referralUrl = null;
  if (referralCode && UUID_RE.test(referralCode)) {
    referralUrl = `${SIGNUP_BASE}?signup=1&signup_source=chatgpt&ref=${referralCode.toLowerCase()}`;
  }
  return { signupUrl, referralUrl };
}
var how_welile_works_default = defineTool({
  name: "how_welile_works",
  title: "How Welile works",
  description: "Explain how Welile Receipts works for new users (tenants, agents, landlords, and Supporters) and return the signup link. Optionally personalise with a referral code to return a referral signup link. No sign-in required \u2014 safe for prospective users.",
  inputSchema: {
    topic: z.string().describe(
      "Optional keyword to focus the answer (e.g. 'tenant', 'agent', 'supporter', 'landlord', 'trust score'). Omit to get all FAQs."
    ).optional(),
    referral_code: z.string().describe("Optional referral code (the referrer's Welile user id) to build a referral signup link.").optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ topic, referral_code }) => {
    const term = (topic ?? "").trim().toLowerCase();
    const matched = term ? FAQS.filter(
      (f) => f.q.toLowerCase().includes(term) || f.a.toLowerCase().includes(term) || f.tags.some((t) => t.includes(term) || term.includes(t))
    ) : FAQS;
    const faqs = matched.length > 0 ? matched : FAQS;
    const { signupUrl, referralUrl } = buildLinks(referral_code);
    const faqText = faqs.map((f) => `Q: ${f.q}
A: ${f.a}`).join("\n\n");
    const linkText = referralUrl ? `Sign up: ${signupUrl}
Referral signup link: ${referralUrl}` : `Sign up: ${signupUrl}`;
    return {
      content: [{ type: "text", text: `${faqText}

---
${linkText}` }],
      structuredContent: {
        faqs: faqs.map(({ q, a }) => ({ question: q, answer: a })),
        signup_url: signupUrl,
        referral_url: referralUrl,
        currency: "UGX"
      }
    };
  }
});

// src/lib/mcp-public/index.ts
var mcp_public_default = defineMcp({
  name: "welile-public-mcp",
  title: "Welile Receipts \u2014 Get Started",
  version: "0.1.0",
  instructions: "Public information about Welile Receipts for prospective users. Use `how_welile_works` to explain the platform (tenants, agents, landlords, Supporters) and return a free signup link \u2014 no account required. All amounts are in UGX.",
  tools: [how_welile_works_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_public_default, { functionName: "mcp-public" }));
