// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp-public
// Bundled from src/lib/mcp-public/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp-public/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp-public/tools/how-welile-works.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^4.4.3";

// src/lib/mcp-public/links.ts
var SIGNUP_BASE = "https://welileapp.com/auth";
var LANDING_BASE = "https://welileapp.com/ai";
var SIGNUP_ROLES = ["tenant", "agent", "landlord", "supporter"];
var UUID_RE = /^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
function buildSignupLinks(opts) {
  const source = (opts?.source ?? "chatgpt").trim() || "chatgpt";
  const params = new URLSearchParams({ signup: "1", signup_source: source });
  if (opts?.role && SIGNUP_ROLES.includes(opts.role)) params.set("role", opts.role);
  const signupUrl = `${SIGNUP_BASE}?${params.toString()}`;
  let referralUrl = null;
  const ref = (opts?.referralCode ?? "").trim();
  if (ref && UUID_RE.test(ref)) {
    const refParams = new URLSearchParams(params);
    refParams.set("ref", ref.toLowerCase());
    referralUrl = `${SIGNUP_BASE}?${refParams.toString()}`;
  }
  const landingParams = new URLSearchParams({ signup_source: source });
  if (opts?.role && SIGNUP_ROLES.includes(opts.role)) landingParams.set("role", opts.role);
  if (ref && UUID_RE.test(ref)) landingParams.set("ref", ref.toLowerCase());
  const landingUrl = `${LANDING_BASE}?${landingParams.toString()}`;
  return { signupUrl, referralUrl, landingUrl };
}

// src/lib/mcp-public/rateLimit.ts
import { createClient } from "npm:@supabase/supabase-js@2.89.0";

// src/lib/mcp-public/response.ts
var PUBLIC_TOOL_SCHEMA_VERSION = "1.0";
var CURRENCY = "UGX";
var FALLBACK_LINKS = {
  landing_url: "https://welileapp.com",
  signup_url: "https://welileapp.com/auth",
  referral_url: null,
  role: null
};
function renderText(e, body) {
  const blocks = [e.summary];
  const trimmedBody = body.filter((b) => b != null && b !== "");
  if (trimmedBody.length) blocks.push(trimmedBody.join("\n"));
  if (e.assumptions.length) {
    blocks.push(`Assumptions:
${e.assumptions.map((a) => `\u2022 ${a}`).join("\n")}`);
  }
  if (e.disclaimers.length) blocks.push(e.disclaimers.join(" "));
  if (e.next_steps.length) {
    blocks.push(`Next step${e.next_steps.length === 1 ? "" : "s"}:
${e.next_steps.map((s) => `\u2022 ${s}`).join("\n")}`);
  }
  const links = [
    `Start here (guided onboarding): ${e.links.landing_url}`,
    `Create a free account: ${e.links.signup_url}`,
    e.links.referral_url ? `Referral signup link: ${e.links.referral_url}` : null
  ].filter(Boolean);
  blocks.push(links.join("\n"));
  return blocks.join("\n\n");
}
function publicToolResult(args) {
  const error = args.error ? {
    code: args.error.code,
    message: args.error.message,
    retry_after_seconds: args.error.retry_after_seconds ?? null,
    details: args.error.details ?? null
  } : null;
  const envelope = {
    schema_version: PUBLIC_TOOL_SCHEMA_VERSION,
    tool: args.tool,
    ok: !error,
    kind: error ? "error" : args.kind ?? "info",
    summary: args.summary,
    assumptions: args.assumptions ?? [],
    estimates: args.estimates ?? null,
    data: args.data ?? {},
    disclaimers: args.disclaimers ?? [],
    next_steps: args.next_steps ?? [],
    links: { ...FALLBACK_LINKS, ...args.links ?? {} },
    currency: CURRENCY,
    error
  };
  const result = {
    content: [{ type: "text", text: renderText(envelope, args.body ?? []) }],
    structuredContent: envelope
  };
  if (error) result.isError = true;
  return result;
}
var ugx = (n) => n == null || !Number.isFinite(n) ? "UGX \u2014" : `UGX ${Math.round(n).toLocaleString("en-US")}`;
function pointRange(label, metric, value, unit = CURRENCY, period = null, breakdown = null) {
  return { label, metric, unit, low: Math.round(value), high: Math.round(value), period, breakdown };
}
function spanRange(label, metric, low, high, unit = CURRENCY, period = null, breakdown = null) {
  return {
    label,
    metric,
    unit,
    low: Math.round(Math.min(low, high)),
    high: Math.round(Math.max(low, high)),
    period,
    breakdown
  };
}

// src/lib/mcp-public/rateLimit.ts
var PER_MINUTE = 30;
var PER_HOUR = 300;
var HASH_PEPPER = "welile-mcp-public-v1";
function readEnv(name) {
  const g = globalThis;
  return g.Deno?.env?.get?.(name) ?? g.process?.env?.[name];
}
var callerStore;
var lastCaller;
var installed = false;
function firstForwardedIp(header) {
  if (!header) return void 0;
  const first = header.split(",")[0]?.trim();
  return first || void 0;
}
function callerFromRequest(request, info) {
  const headers = request.headers;
  const forwarded = firstForwardedIp(headers.get("x-forwarded-for")) ?? headers.get("cf-connecting-ip") ?? headers.get("x-real-ip") ?? void 0;
  if (forwarded) return forwarded;
  const remote = info?.remoteAddr;
  return remote?.hostname ?? void 0;
}
function installCallerCapture() {
  if (installed) return;
  installed = true;
  const g = globalThis;
  const deno = g.Deno;
  const originalServe = deno?.serve;
  if (!deno || typeof originalServe !== "function") return;
  deno.serve = (...args) => {
    const wrapped = args.map(
      (arg) => typeof arg === "function" ? (request, info) => {
        const caller = callerFromRequest(request, info);
        lastCaller = caller;
        const call = () => arg(request, info);
        return callerStore ? callerStore.run(caller, call) : call();
      } : arg
    );
    return originalServe.apply(deno, wrapped);
  };
  void (async () => {
    try {
      const mod = await import(
        /* @vite-ignore */
        "node:async_hooks"
      );
      if (mod.AsyncLocalStorage) callerStore = new mod.AsyncLocalStorage();
    } catch {
    }
  })();
}
installCallerCapture();
function currentCaller() {
  return callerStore?.getStore() ?? lastCaller;
}
async function hashCaller(ip) {
  try {
    const bytes = new TextEncoder().encode(`${HASH_PEPPER}:${ip}`);
    const digest = await crypto.subtle.digest("SHA-256", bytes);
    return Array.from(new Uint8Array(digest)).map((b) => b.toString(16).padStart(2, "0")).join("");
  } catch {
    return void 0;
  }
}
function publishableKey() {
  const direct = readEnv("SUPABASE_PUBLISHABLE_KEY") ?? readEnv("VITE_SUPABASE_PUBLISHABLE_KEY");
  if (direct) return direct;
  const keyset = readEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find(
          (v) => typeof v === "string" && v.trim().startsWith("sb_publishable_")
        );
        if (key) return key.trim();
      }
    } catch {
    }
  }
  return readEnv("SUPABASE_ANON_KEY") ?? readEnv("VITE_SUPABASE_ANON_KEY");
}
function limiterClient() {
  const url = readEnv("SUPABASE_URL") ?? readEnv("VITE_SUPABASE_URL");
  const key = publishableKey();
  if (!url || !key) return void 0;
  return createClient(url, key, {
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
function waitLabel(seconds) {
  if (seconds >= 90) return `about ${Math.round(seconds / 60)} minutes`;
  return `about ${Math.max(5, seconds)} seconds`;
}
async function enforceRateLimit(tool) {
  const ip = currentCaller();
  if (!ip) return null;
  const hash = await hashCaller(ip);
  if (!hash) return null;
  const client = limiterClient();
  if (!client) return null;
  try {
    const { data, error } = await client.rpc("check_mcp_public_rate_limit", {
      p_caller_hash: hash,
      p_tool: tool,
      p_per_minute: PER_MINUTE,
      p_per_hour: PER_HOUR
    });
    if (error) return null;
    const verdict = data ?? {};
    if (verdict.allowed !== false) return null;
    const retry = Math.max(1, Math.round(verdict.retry_after_seconds ?? 60));
    const blocked = verdict.reason === "temporarily_blocked";
    const text = blocked ? `Too many requests from this connection, so it is paused for ${waitLabel(retry)}. This limit protects the free public Welile tools from spam. Please try again after that, or create a free account at https://welileapp.com for your own personal access.` : `Rate limit reached \u2014 the free public Welile tools allow ${PER_MINUTE} requests a minute and ${PER_HOUR} an hour per connection. Please try again in ${waitLabel(retry)}, or create a free account at https://welileapp.com for your own personal access.`;
    return publicToolResult({
      tool,
      summary: text,
      next_steps: ["Create a free Welile account for your own personal access, with no shared limit."],
      data: {
        limit_per_minute: PER_MINUTE,
        limit_per_hour: PER_HOUR
      },
      error: {
        code: "rate_limited",
        message: verdict.reason ?? "rate_limited",
        retry_after_seconds: retry,
        details: { limit_per_minute: PER_MINUTE, limit_per_hour: PER_HOUR }
      }
    });
  } catch {
    return null;
  }
}

// src/lib/mcp-public/tools/how-welile-works.ts
var GUIDED_PROMPTS = [
  "Check my rent access",
  "See agent commissions",
  "See supporter Returns",
  "Get guaranteed rent as a landlord",
  "Check my Welile Trust Score"
];
var FAQS = [
  {
    q: "What is Welile?",
    a: "Welile is a Ugandan platform that helps tenants access rent through a flexible Rent Plan, backed by community Supporters and served on the ground by field agents. All amounts are in Ugandan Shillings (UGX).",
    tags: ["about", "what", "welile", "overview"]
  },
  {
    q: "How do I get rent help as a tenant?",
    a: "Create a free account, complete verification (your national ID and residence), and an agent or landlord connects you to a Rent Plan. You then repay in small, regular amounts that fit your income.",
    tags: ["tenant", "rent", "help", "how", "repay"]
  },
  {
    q: "How do agents earn on Welile?",
    a: "Agents register tenants, list houses, and collect rent in the field. They earn commission on the collections and placements they make, tracked in a wallet they can withdraw from.",
    tags: ["agent", "earn", "commission", "work", "job"]
  },
  {
    q: "How can I support tenants and earn Returns?",
    a: "Become a Supporter: your funds help tenants access rent, and you earn periodic Returns. Rates and terms are shown in the app when you sign up. (Terminology: Supporter, not lender; Returns, not interest.)",
    tags: ["supporter", "invest", "fund", "returns", "earn"]
  },
  {
    q: "How does a landlord benefit?",
    a: "Landlords list their houses and receive guaranteed, on-time rent instead of chasing tenants each month. Welile handles collection through its agent network.",
    tags: ["landlord", "house", "rent", "guarantee"]
  },
  {
    q: "What is the Welile Trust Score / AI ID?",
    a: "Every user builds a Welile Trust Score \u2014 a reliability identity based on real behaviour like on-time payments and verification. A higher score unlocks better access over time.",
    tags: ["trust", "score", "ai id", "identity", "reliability"]
  },
  {
    q: "Is Welile free to join?",
    a: "Yes, creating an account is free. You only ever deal in UGX, and you can start as a tenant, agent, landlord, or Supporter.",
    tags: ["free", "cost", "join", "signup", "price"]
  },
  {
    q: "How do I check what I personally qualify for?",
    a: "Personal figures \u2014 your rent access, wallet balance, commissions, or Returns \u2014 are shown once you create a free account and sign in. Ask 'check my rent access' or 'see agent commissions' to get started, and I'll share the right signup link.",
    tags: ["check", "qualify", "balance", "personal", "account", "my"]
  },
  {
    q: "Is my money safe and what currency is used?",
    a: "Welile operates strictly in Ugandan Shillings (UGX). Every balance, Rent Plan, commission, and Return is recorded in UGX, and your account activity is tied to your verified identity.",
    tags: ["safe", "security", "currency", "ugx", "money"]
  }
];
var how_welile_works_default = defineTool({
  name: "how_welile_works",
  title: "How Welile works",
  description: "Explain how Welile Receipts works for new users (tenants, agents, landlords, and Supporters) and return the signup link. Optionally personalise with a referral code to return a referral signup link. No sign-in required \u2014 safe for prospective users.",
  inputSchema: {
    topic: z.string().describe(
      "Optional keyword to focus the answer (e.g. 'tenant', 'agent', 'supporter', 'landlord', 'trust score'). Omit to get all FAQs."
    ).optional(),
    referral_code: z.string().describe("Optional referral code (the referrer's Welile user id) to build a referral signup link.").optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ topic, referral_code }) => {
    const limited = await enforceRateLimit("how_welile_works");
    if (limited) return limited;
    const term = (topic ?? "").trim().toLowerCase();
    const matched = term ? FAQS.filter(
      (f) => f.q.toLowerCase().includes(term) || f.tags.some((t) => t.includes(term) || term.includes(t))
    ) : FAQS;
    const faqs = matched.length > 0 ? matched : FAQS;
    const { signupUrl, referralUrl, landingUrl } = buildSignupLinks({ referralCode: referral_code });
    const faqText = faqs.map((f) => `Q: ${f.q}
A: ${f.a}`).join("\n\n");
    return publicToolResult({
      tool: "how_welile_works",
      kind: "info",
      summary: term ? `How Welile works \u2014 ${faqs.length} answer${faqs.length === 1 ? "" : "s"} about "${term}". All amounts are in UGX.` : "How Welile works: tenants access rent through a flexible Rent Plan, agents serve them in the field, landlords get guaranteed rent, and Supporters earn Returns. All amounts are in UGX.",
      body: [faqText, "", `Try asking:
${GUIDED_PROMPTS.map((p) => `\u2022 ${p}`).join("\n")}`],
      assumptions: [
        "General product information only \u2014 nothing here is specific to one person's account.",
        "Every amount on Welile is in Ugandan Shillings (UGX)."
      ],
      data: {
        matched_topic: term || null,
        faqs: faqs.map(({ q, a }) => ({ question: q, answer: a })),
        guided_prompts: GUIDED_PROMPTS
      },
      disclaimers: [
        "Personal figures (your rent access, wallet, commissions, or Returns) are only visible after you create a free account and sign in."
      ],
      next_steps: [
        "Create a free account to see what you personally qualify for.",
        "Ask one of the guided prompts above for a specific ballpark."
      ],
      links: { landing_url: landingUrl, signup_url: signupUrl, referral_url: referralUrl }
    });
  }
});

// src/lib/mcp-public/tools/explore-welile.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^4.4.3";
var FEATURES = [
  {
    intent: "rent_access",
    prompt: "Check my rent access",
    role: "tenant",
    headline: "Access rent with a flexible Rent Plan",
    explanation: "As a tenant you can get help paying rent through a Rent Plan and repay in small, regular UGX amounts that fit your income. To see the amount you qualify for, you create a free account and complete verification (national ID and residence) \u2014 an agent or landlord then connects you to a Rent Plan.",
    next_step: "Create a free tenant account to check your personal rent access and start a Rent Plan."
  },
  {
    intent: "agent_commissions",
    prompt: "See agent commissions",
    role: "agent",
    headline: "Earn commission as a field agent",
    explanation: "Agents register tenants, list houses, and collect rent in the field. You earn commission in UGX on the collections and placements you make, tracked in a wallet you can withdraw from. Your exact earnings and wallet balance are shown once you sign in.",
    next_step: "Create a free agent account to see your commission wallet and start earning."
  },
  {
    intent: "supporter_returns",
    prompt: "See supporter Returns",
    role: "supporter",
    headline: "Support tenants and earn Returns",
    explanation: "As a Supporter your funds help tenants access rent, and you earn periodic Returns in UGX. Rates and terms are shown in the app when you sign up. (Terminology: Supporter, not lender; Returns, not interest.)",
    next_step: "Create a free Supporter account to view current Returns and start supporting tenants."
  },
  {
    intent: "landlord_payouts",
    prompt: "Get guaranteed rent as a landlord",
    role: "landlord",
    headline: "Guaranteed, on-time rent for landlords",
    explanation: "Landlords list their houses and receive guaranteed, on-time rent in UGX instead of chasing tenants each month. Welile handles collection through its agent network.",
    next_step: "Create a free landlord account to list a house and receive guaranteed rent."
  },
  {
    intent: "trust_score",
    prompt: "Check my Welile Trust Score",
    headline: "Build a Welile Trust Score",
    explanation: "Every user builds a Welile Trust Score \u2014 a reliability identity based on real behaviour like on-time payments and verification. A higher score unlocks better access over time. Your personal score appears once you sign in.",
    next_step: "Create a free account to start building your Welile Trust Score."
  }
];
function matchFeature(intent) {
  const term = (intent ?? "").trim().toLowerCase();
  if (!term) return null;
  return FEATURES.find((f) => f.intent === term) ?? FEATURES.find(
    (f) => f.prompt.toLowerCase().includes(term) || f.headline.toLowerCase().includes(term) || term.includes(f.intent.split("_")[0])
  ) ?? null;
}
var explore_welile_default = defineTool2({
  name: "explore_welile",
  title: "Explore Welile (guided prompts)",
  description: "Answer a prospective user's read-only question about what Welile can do for them (e.g. 'check my rent access', 'see agent commissions', 'supporter Returns', 'landlord payouts', 'Trust Score') and return a role-targeted free signup link so they can act. No sign-in required. Amounts in UGX. If no intent is given, returns the full list of guided prompts to suggest.",
  inputSchema: {
    intent: z2.string().describe(
      "The user's goal. One of: rent_access, agent_commissions, supporter_returns, landlord_payouts, trust_score \u2014 or free text like 'check my rent access'. Omit to list all guided prompts."
    ).optional(),
    referral_code: z2.string().describe("Optional referral code (the referrer's Welile user id) to build a referral signup link.").optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ intent, referral_code }) => {
    const limited = await enforceRateLimit("explore_welile");
    if (limited) return limited;
    const feature = matchFeature(intent);
    if (feature) {
      const { signupUrl: signupUrl2, referralUrl, landingUrl: landingUrl2 } = buildSignupLinks({
        referralCode: referral_code,
        role: feature.role
      });
      return publicToolResult({
        tool: "explore_welile",
        kind: "info",
        summary: feature.headline,
        body: [feature.explanation],
        assumptions: [
          "General explanation of the feature \u2014 not a figure calculated for your account.",
          "All amounts on Welile are in Ugandan Shillings (UGX)."
        ],
        data: {
          matched_intent: feature.intent,
          headline: feature.headline,
          explanation: feature.explanation,
          guided_prompts: null
        },
        disclaimers: [
          "Your personal figures appear only after you create a free account and sign in."
        ],
        next_steps: [feature.next_step],
        links: {
          landing_url: landingUrl2,
          signup_url: signupUrl2,
          referral_url: referralUrl,
          role: feature.role ?? null
        }
      });
    }
    const prompts = FEATURES.map((f) => {
      const { signupUrl: signupUrl2, landingUrl: landingUrl2 } = buildSignupLinks({ referralCode: referral_code, role: f.role });
      return {
        prompt: f.prompt,
        intent: f.intent,
        headline: f.headline,
        role: f.role ?? null,
        landing_url: landingUrl2,
        signup_url: signupUrl2
      };
    });
    const menuText = [
      "Ask about any of these to get started with Welile (UGX):",
      ...prompts.map((p) => `\u2022 ${p.prompt}`)
    ].join("\n");
    const { signupUrl, landingUrl } = buildSignupLinks({ referralCode: referral_code });
    return publicToolResult({
      tool: "explore_welile",
      kind: "info",
      summary: `Welile can help you in ${prompts.length} ways \u2014 ask about any of these to get a real ballpark in UGX.`,
      body: [menuText],
      assumptions: [
        "No specific goal was given, so this is the full menu of guided prompts.",
        "All amounts on Welile are in Ugandan Shillings (UGX)."
      ],
      data: {
        matched_intent: null,
        headline: null,
        explanation: null,
        guided_prompts: prompts
      },
      next_steps: prompts.map((p) => `Ask: "${p.prompt}"`),
      links: { landing_url: landingUrl, signup_url: signupUrl }
    });
  }
});

// src/lib/mcp-public/tools/estimate-rent-access.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z3 } from "npm:zod@^4.4.3";
var MONTHLY_RATE = 0.33;
var DEFAULT_DURATIONS = [30, 60, 90];
var AGENT_COMMISSION_RATE = 0.1;
var MIN_RENT = 1e4;
var MAX_RENT = 5e6;
var MIN_DAYS = 7;
var MAX_DAYS = 120;
function computeRentPlan(rent, days) {
  const accessFee = Math.round(rent * (Math.pow(1 + MONTHLY_RATE, days / 30) - 1));
  const requestFee = rent <= 2e5 ? 1e4 : 2e4;
  const totalRepayment = rent + accessFee + requestFee;
  const dailyRepayment = Math.ceil(totalRepayment / days);
  const agentCommission = Math.min(Math.round(rent * AGENT_COMMISSION_RATE), accessFee);
  const accessFeeNet = accessFee - agentCommission;
  const serviceFee = requestFee;
  return {
    durationDays: days,
    principalRent: rent,
    accessFee,
    accessFeeNet,
    agentCommission,
    serviceFee,
    requestFee,
    totalRepayment,
    dailyRepayment
  };
}
var estimate_rent_access_default = defineTool3({
  name: "estimate_rent_access",
  title: "Estimate rent access (indicative)",
  description: "Give a prospective tenant an INDICATIVE rent-access ballpark in UGX \u2014 total repayment and daily payment for a given monthly rent \u2014 then return the free tenant signup link. No sign-in required. Amounts are illustrative only, not an approval or guarantee; the actual Rent Plan is set after signup and verification. Provide `rent` (monthly rent in UGX). Optionally provide `duration_days` (7-120) for one plan, otherwise 30/60/90-day options are returned. Optional `referral_code` adds a referral signup link.",
  inputSchema: {
    rent: z3.number().describe("Monthly rent in UGX (e.g. 200000). Ballpark only."),
    duration_days: z3.number().describe("Optional Rent Plan length in days (7-120). Omit to compare 30/60/90-day options.").optional(),
    referral_code: z3.string().describe("Optional referral code (the referrer's Welile user id) to build a referral signup link.").optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ rent, duration_days, referral_code }) => {
    const limited = await enforceRateLimit("estimate_rent_access");
    if (limited) return limited;
    const { signupUrl, referralUrl, landingUrl } = buildSignupLinks({
      referralCode: referral_code,
      role: "tenant"
    });
    const links = { landing_url: landingUrl, signup_url: signupUrl, referral_url: referralUrl, role: "tenant" };
    const DISCLAIMERS = [
      "This is an indicative ballpark, not an approval or a guarantee.",
      "Your actual Rent Plan is confirmed after you create a free account and complete verification (national ID and residence)."
    ];
    if (!Number.isFinite(rent) || rent < MIN_RENT || rent > MAX_RENT) {
      return publicToolResult({
        tool: "estimate_rent_access",
        summary: `Please share a monthly rent between ${ugx(MIN_RENT)} and ${ugx(MAX_RENT)} for an indicative estimate.`,
        next_steps: [`Ask again with a monthly rent in UGX, for example ${ugx(2e5)}.`],
        links,
        error: {
          code: "invalid_rent",
          message: `Monthly rent must be between ${MIN_RENT} and ${MAX_RENT} UGX.`,
          details: { min_rent: MIN_RENT, max_rent: MAX_RENT }
        }
      });
    }
    const roundedRent = Math.round(rent);
    let durations;
    if (duration_days != null) {
      const d = Math.round(duration_days);
      if (!Number.isFinite(d) || d < MIN_DAYS || d > MAX_DAYS) {
        return publicToolResult({
          tool: "estimate_rent_access",
          summary: `Rent Plan length must be between ${MIN_DAYS} and ${MAX_DAYS} days. Try 30, 60, or 90 days.`,
          next_steps: ["Ask again with a plan length of 30, 60, or 90 days."],
          links,
          error: {
            code: "invalid_duration",
            message: `Plan length must be between ${MIN_DAYS} and ${MAX_DAYS} days.`,
            details: { min_days: MIN_DAYS, max_days: MAX_DAYS }
          }
        });
      }
      durations = [d];
    } else {
      durations = [...DEFAULT_DURATIONS];
    }
    const plans = durations.map((d) => computeRentPlan(roundedRent, d));
    const planBlocks = plans.map(
      (p) => [
        `${p.durationDays}-day plan \u2014 total ~${ugx(p.totalRepayment)} (about ${ugx(p.dailyRepayment)}/day)`,
        `    \u2022 Rent paid to landlord: ${ugx(p.principalRent)}`,
        `    \u2022 Access fee (financing): ${ugx(p.accessFeeNet)}`,
        `    \u2022 Agent commission: ${ugx(p.agentCommission)}`,
        `    \u2022 Service fee: ${ugx(p.serviceFee)}`
      ].join("\n")
    ).join("\n\n");
    const ranges = [];
    for (const p of plans) {
      const period = { unit: "days", value: p.durationDays };
      ranges.push(
        pointRange(`${p.durationDays}-day plan total`, "total_repayment", p.totalRepayment, "UGX", period, {
          principal_rent: p.principalRent,
          access_fee: p.accessFeeNet,
          agent_commission: p.agentCommission,
          service_fee: p.serviceFee,
          total: p.totalRepayment
        }),
        pointRange(`${p.durationDays}-day plan daily payment`, "daily_repayment", p.dailyRepayment, "UGX_per_day", period)
      );
    }
    if (plans.length > 1) {
      const totals = plans.map((p) => p.totalRepayment);
      const dailies = plans.map((p) => p.dailyRepayment);
      ranges.push(
        spanRange("Total repayment across plans compared", "total_repayment_span", Math.min(...totals), Math.max(...totals)),
        spanRange("Daily payment across plans compared", "daily_repayment_span", Math.min(...dailies), Math.max(...dailies), "UGX_per_day")
      );
    }
    return publicToolResult({
      tool: "estimate_rent_access",
      kind: "estimate",
      summary: `Indicative Rent Plan for a monthly rent of ${ugx(roundedRent)}: total ${plans.length > 1 ? `${ugx(Math.min(...plans.map((p) => p.totalRepayment)))}\u2013${ugx(Math.max(...plans.map((p) => p.totalRepayment)))}` : ugx(plans[0].totalRepayment)} depending on plan length.`,
      body: [planBlocks],
      assumptions: [
        `Access fee compounds at ${MONTHLY_RATE * 100}% a month over the plan length.`,
        `Service fee is ${ugx(1e4)} for rent up to ${ugx(2e5)}, otherwise ${ugx(2e4)}.`,
        `Agent commission shown is ${AGENT_COMMISSION_RATE * 100}% of rent, carved out of the access fee \u2014 it is never added on top, so the total is unchanged.`,
        plans.length > 1 ? `No plan length was given, so ${DEFAULT_DURATIONS.join("/")}-day options are compared.` : `Plan length of ${plans[0].durationDays} days as requested.`,
        "Daily payment is the total divided over the plan length, rounded up."
      ],
      estimates: {
        basis: `Welile's canonical Rent Plan formula: rent + access fee (${MONTHLY_RATE * 100}% monthly compound) + service fee, repaid over the plan length.`,
        confidence: "indicative",
        currency: "UGX",
        ranges
      },
      data: {
        rent: roundedRent,
        monthly_rate_pct: MONTHLY_RATE * 100,
        plans: plans.map((p) => ({
          duration_days: p.durationDays,
          daily_repayment: p.dailyRepayment,
          total_repayment: p.totalRepayment,
          access_fee: p.accessFee,
          request_fee: p.requestFee,
          breakdown: {
            principal_rent: p.principalRent,
            access_fee: p.accessFeeNet,
            agent_commission: p.agentCommission,
            service_fee: p.serviceFee,
            total: p.totalRepayment
          }
        }))
      },
      disclaimers: [
        "Line items are illustrative only \u2014 the service/access/agent-commission split is shown for transparency and does not change the total.",
        ...DISCLAIMERS
      ],
      next_steps: [
        "Create a free tenant account to see the Rent Plan you personally qualify for.",
        "Ask to find available houses in your district to see real rents."
      ],
      links
    });
  }
});

// src/lib/mcp-public/tools/estimate-supporter-returns.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z4 } from "npm:zod@^4.4.3";
var REWARD_RATE = 0.15;
var DEFAULT_DURATIONS2 = [3, 6, 12];
var MIN_AMOUNT = 2e4;
var MAX_AMOUNT = 5e8;
var MIN_MONTHS = 1;
var MAX_MONTHS = 36;
function project(amount, months) {
  const monthlyReward = amount * REWARD_RATE;
  const simpleEarnings = monthlyReward * months;
  const simpleTotal = amount + simpleEarnings;
  let balance = amount;
  for (let m = 1; m <= months; m++) balance += balance * REWARD_RATE;
  const compoundEarnings = balance - amount;
  return {
    durationMonths: months,
    monthlyReward: Math.round(monthlyReward),
    simpleEarnings: Math.round(simpleEarnings),
    simpleTotal: Math.round(simpleTotal),
    compoundEarnings: Math.round(compoundEarnings),
    compoundTotal: Math.round(balance)
  };
}
var estimate_supporter_returns_default = defineTool4({
  name: "estimate_supporter_returns",
  title: "Estimate Supporter Returns (illustrative)",
  description: "Give a prospective Supporter an ILLUSTRATIVE Returns range in UGX for a chosen support amount over time (based on 15% monthly platform rewards), then return the free Supporter signup link. No sign-in required. The range spans simple (rewards paid out) to compounding (rewards reinvested) \u2014 it is an illustration only, not a guarantee; actual rates and terms are shown in the app after signup. Provide `amount` (UGX to support). Optionally provide `duration_months` (1-36) for one horizon, otherwise 3/6/12-month options are returned. Optional `referral_code` adds a referral signup link. (Terminology: Supporter, not lender; Returns, not interest.)",
  inputSchema: {
    amount: z4.number().describe("Amount to support in UGX (e.g. 500000). Illustration only."),
    duration_months: z4.number().describe("Optional horizon in months (1-36). Omit to compare 3/6/12-month options.").optional(),
    referral_code: z4.string().describe("Optional referral code (the referrer's Welile user id) to build a referral signup link.").optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ amount, duration_months, referral_code }) => {
    const limited = await enforceRateLimit("estimate_supporter_returns");
    if (limited) return limited;
    const { signupUrl, referralUrl, landingUrl } = buildSignupLinks({
      referralCode: referral_code,
      role: "supporter"
    });
    const links = { landing_url: landingUrl, signup_url: signupUrl, referral_url: referralUrl, role: "supporter" };
    if (!Number.isFinite(amount) || amount < MIN_AMOUNT || amount > MAX_AMOUNT) {
      return publicToolResult({
        tool: "estimate_supporter_returns",
        summary: `Please share a support amount between ${ugx(MIN_AMOUNT)} and ${ugx(MAX_AMOUNT)} for an illustrative estimate.`,
        next_steps: [`Ask again with an amount in UGX, for example ${ugx(5e5)}.`],
        links,
        error: {
          code: "invalid_amount",
          message: `Support amount must be between ${MIN_AMOUNT} and ${MAX_AMOUNT} UGX.`,
          details: { min_amount: MIN_AMOUNT, max_amount: MAX_AMOUNT }
        }
      });
    }
    const roundedAmount = Math.round(amount);
    let months;
    if (duration_months != null) {
      const m = Math.round(duration_months);
      if (!Number.isFinite(m) || m < MIN_MONTHS || m > MAX_MONTHS) {
        return publicToolResult({
          tool: "estimate_supporter_returns",
          summary: `Horizon must be between ${MIN_MONTHS} and ${MAX_MONTHS} months. Try 3, 6, or 12 months.`,
          next_steps: ["Ask again with a horizon of 3, 6, or 12 months."],
          links,
          error: {
            code: "invalid_duration",
            message: `Horizon must be between ${MIN_MONTHS} and ${MAX_MONTHS} months.`,
            details: { min_months: MIN_MONTHS, max_months: MAX_MONTHS }
          }
        });
      }
      months = [m];
    } else {
      months = [...DEFAULT_DURATIONS2];
    }
    const projections = months.map((m) => project(roundedAmount, m));
    const lines = projections.map(
      (p) => `\u2022 ${p.durationMonths} month${p.durationMonths === 1 ? "" : "s"}: Returns of ${ugx(p.simpleEarnings)} (paid out) to ${ugx(p.compoundEarnings)} (reinvested)`
    ).join("\n");
    const ranges = [];
    for (const p of projections) {
      const period = { unit: "months", value: p.durationMonths };
      ranges.push(
        spanRange(`Returns over ${p.durationMonths} month${p.durationMonths === 1 ? "" : "s"}`, "returns", p.simpleEarnings, p.compoundEarnings, "UGX", period, {
          paid_out: p.simpleEarnings,
          reinvested: p.compoundEarnings
        }),
        spanRange(`Total value after ${p.durationMonths} month${p.durationMonths === 1 ? "" : "s"}`, "total_value", p.simpleTotal, p.compoundTotal, "UGX", period, {
          principal: roundedAmount,
          paid_out_total: p.simpleTotal,
          reinvested_total: p.compoundTotal
        }),
        pointRange("Monthly reward (first month)", "monthly_reward", p.monthlyReward, "UGX_per_month", period)
      );
    }
    const allReturns = projections.flatMap((p) => [p.simpleEarnings, p.compoundEarnings]);
    return publicToolResult({
      tool: "estimate_supporter_returns",
      kind: "estimate",
      summary: `Illustrative Returns for supporting ${ugx(roundedAmount)}: ${ugx(Math.min(...allReturns))}\u2013${ugx(
        Math.max(...allReturns)
      )} depending on horizon and whether Returns are paid out or reinvested.`,
      body: [lines],
      assumptions: [
        `Platform rewards of ${REWARD_RATE * 100}% a month on the supported amount.`,
        "Low end of each range = Returns paid out monthly; high end = Returns reinvested (compounding).",
        projections.length > 1 ? `No horizon was given, so ${DEFAULT_DURATIONS2.join("/")}-month options are compared.` : `Horizon of ${projections[0].durationMonths} month${projections[0].durationMonths === 1 ? "" : "s"} as requested.`,
        "Principal is assumed to stay in place for the whole horizon, with no withdrawal."
      ],
      estimates: {
        basis: `${REWARD_RATE * 100}% monthly platform rewards, shown both paid out (simple) and reinvested (compounding).`,
        confidence: "illustrative",
        currency: "UGX",
        ranges
      },
      data: {
        amount: roundedAmount,
        monthly_reward_rate_pct: REWARD_RATE * 100,
        projections: projections.map((p) => ({
          duration_months: p.durationMonths,
          monthly_reward: p.monthlyReward,
          simple_earnings: p.simpleEarnings,
          simple_total: p.simpleTotal,
          compound_earnings: p.compoundEarnings,
          compound_total: p.compoundTotal
        }))
      },
      disclaimers: [
        "This is an illustration only \u2014 not a guarantee of Returns.",
        "Actual rates and terms are shown in the app after you create a free account.",
        "Supporter withdrawals require a 90-day notice period."
      ],
      next_steps: [
        "Create a free Supporter account to view current Returns and start supporting tenants."
      ],
      links
    });
  }
});

// src/lib/mcp-public/tools/find-available-houses.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@2.89.0";
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z5 } from "npm:zod@^4.4.3";
var DEFAULT_LIMIT = 5;
var MAX_LIMIT = 10;
function readEnv2(name) {
  const g = globalThis;
  return g.Deno?.env?.get(name) ?? g.process?.env?.[name];
}
function anonClient() {
  const url = readEnv2("SUPABASE_URL");
  const anonKey = readEnv2("SUPABASE_PUBLISHABLE_KEY") ?? readEnv2("SUPABASE_ANON_KEY");
  if (!url || !anonKey) throw new Error("Supabase env not configured");
  return createClient2(url, anonKey, {
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
function amenityList(r) {
  const out = [];
  if (r.has_water) out.push("water");
  if (r.has_electricity) out.push("electricity");
  if (r.has_security) out.push("security");
  if (r.has_parking) out.push("parking");
  if (r.is_furnished) out.push("furnished");
  return out;
}
function locationLabel(r) {
  return [r.village, r.sub_county, r.district, r.region].filter(Boolean).join(", ") || "Location on request";
}
var find_available_houses_default = defineTool5({
  name: "find_available_houses",
  title: "Find available houses",
  description: "Return a small read-only sample of AVAILABLE Welile house listings for a prospective tenant, filtered by district and/or area, then return the free tenant signup link to view details and apply. No sign-in required. Only public, non-sensitive fields are shown (no exact address, GPS, landlord, or contact details). Amounts are in UGX. Provide `district` and/or `area` to narrow the search, optional `max_rent` (UGX) and `limit` (1-10, default 5), and optional `referral_code` for a referral signup link.",
  inputSchema: {
    district: z5.string().describe("Optional district to search (e.g. 'Wakiso', 'Kampala').").optional(),
    area: z5.string().describe("Optional area/neighbourhood \u2014 matches village, sub-county, district, or region.").optional(),
    max_rent: z5.number().describe("Optional maximum monthly rent in UGX.").optional(),
    limit: z5.number().describe("Optional number of listings to return (1-10, default 5).").optional(),
    referral_code: z5.string().describe("Optional referral code (the referrer's Welile user id) to build a referral signup link.").optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ district, area, max_rent, limit, referral_code }) => {
    const limited = await enforceRateLimit("find_available_houses");
    if (limited) return limited;
    const { signupUrl, referralUrl, landingUrl } = buildSignupLinks({
      referralCode: referral_code,
      role: "tenant"
    });
    const links = { landing_url: landingUrl, signup_url: signupUrl, referral_url: referralUrl, role: "tenant" };
    const take = Math.min(MAX_LIMIT, Math.max(1, Math.round(limit ?? DEFAULT_LIMIT)));
    let query = anonClient().from("house_listings").select(
      "id,title,house_category,number_of_rooms,monthly_rent,region,district,sub_county,village,has_water,has_electricity,has_security,has_parking,is_furnished,verified,image_urls"
    ).eq("status", "available").not("is_hidden", "is", true);
    const districtTerm = (district ?? "").trim();
    if (districtTerm) query = query.ilike("district", `%${districtTerm}%`);
    const areaTerm = (area ?? "").trim();
    if (areaTerm) {
      const like = `%${areaTerm}%`;
      query = query.or(
        `village.ilike.${like},sub_county.ilike.${like},district.ilike.${like},region.ilike.${like}`
      );
    }
    if (typeof max_rent === "number" && Number.isFinite(max_rent) && max_rent > 0) {
      query = query.lte("monthly_rent", Math.round(max_rent));
    }
    query = query.order("verified", { ascending: false }).order("created_at", { ascending: false }).limit(take);
    const { data, error } = await query;
    const filters = {
      district: districtTerm || null,
      area: areaTerm || null,
      max_rent: typeof max_rent === "number" && Number.isFinite(max_rent) ? Math.round(max_rent) : null,
      limit: take
    };
    const filterAssumptions = [
      "Only listings currently marked available are searched; verified listings are shown first.",
      districtTerm ? `District filtered to "${districtTerm}".` : "No district filter applied.",
      areaTerm ? `Area matched against village, sub-county, district, or region for "${areaTerm}".` : "No area filter applied.",
      filters.max_rent != null ? `Maximum monthly rent of ${ugx(filters.max_rent)}.` : "No maximum rent applied.",
      `At most ${take} listing${take === 1 ? "" : "s"} returned \u2014 this is a sample, not the full catalogue.`
    ];
    if (error) {
      return publicToolResult({
        tool: "find_available_houses",
        summary: "Sorry, I couldn't fetch listings right now. You can still browse everything after signing up.",
        data: { filters, count: 0, listings: [] },
        next_steps: ["Create a free tenant account to browse all available houses."],
        links,
        error: { code: "listings_unavailable", message: error.message }
      });
    }
    const rows = data ?? [];
    if (rows.length === 0) {
      const where = districtTerm || areaTerm ? ` in "${districtTerm || areaTerm}"` : "";
      return publicToolResult({
        tool: "find_available_houses",
        kind: "listings",
        summary: `No available listings matched your search${where} right now.`,
        body: ["New houses are added regularly."],
        assumptions: filterAssumptions,
        estimates: null,
        data: { filters, count: 0, listings: [] },
        next_steps: [
          "Try a wider area, a nearby district, or a higher maximum rent.",
          "Create a free tenant account to save a search and get matched when a house is listed."
        ],
        links
      });
    }
    const listings = rows.map((r) => ({
      id: r.id,
      title: r.title ?? "Available house",
      category: r.house_category ?? null,
      rooms: r.number_of_rooms ?? null,
      monthly_rent: r.monthly_rent ?? null,
      location: locationLabel(r),
      district: r.district ?? null,
      amenities: amenityList(r),
      verified: !!r.verified,
      photo_count: Array.isArray(r.image_urls) ? r.image_urls.length : 0
    }));
    const lines = listings.map((l) => {
      const bits = [
        `${ugx(l.monthly_rent)}/mo`,
        l.rooms ? `${l.rooms} room${l.rooms === 1 ? "" : "s"}` : null,
        l.location,
        l.amenities.length ? l.amenities.join(", ") : null,
        l.verified ? "\u2713 verified" : null
      ].filter(Boolean);
      return `\u2022 ${l.title} \u2014 ${bits.join(" \xB7 ")}`;
    }).join("\n");
    const rents = listings.map((l) => l.monthly_rent).filter((r) => typeof r === "number" && Number.isFinite(r));
    const ranges = rents.length ? [
      spanRange("Monthly rent across these listings", "monthly_rent", Math.min(...rents), Math.max(...rents), "UGX_per_month", {
        unit: "months",
        value: 1
      })
    ] : [];
    return publicToolResult({
      tool: "find_available_houses",
      kind: "listings",
      summary: `${listings.length} available house${listings.length === 1 ? "" : "s"} on Welile${rents.length ? `, from ${ugx(Math.min(...rents))} to ${ugx(Math.max(...rents))} a month` : ""}.`,
      body: [lines],
      assumptions: filterAssumptions,
      estimates: ranges.length ? {
        basis: "Actual monthly rents recorded on the available listings returned by this search.",
        confidence: "actual",
        currency: "UGX",
        ranges
      } : null,
      data: { filters, count: listings.length, listings },
      disclaimers: [
        "Only public, non-sensitive fields are shown \u2014 no exact address, GPS, landlord, or contact details.",
        "Full details, photos, and contact happen inside the app after you create a free account."
      ],
      next_steps: [
        "Create a free tenant account to view details, photos, and apply.",
        "Ask for an indicative Rent Plan on any of these rents."
      ],
      links
    });
  }
});

// src/lib/mcp-public/index.ts
var mcp_public_default = defineMcp({
  name: "welile-public-mcp",
  title: "Welile Receipts \u2014 Get Started",
  version: "0.1.0",
  instructions: "Public information about Welile Receipts for prospective users \u2014 no account required. Use `how_welile_works` for FAQs and a free signup link. Use `explore_welile` to answer read-only 'what can I do' questions and offer guided prompts such as 'Check my rent access', 'See agent commissions', 'See supporter Returns', 'Get guaranteed rent as a landlord', and 'Check my Welile Trust Score' \u2014 each returns a role-targeted signup link that turns the question into an account. Use `estimate_rent_access` when a prospective tenant gives a monthly rent (UGX) to return an indicative daily/total repayment ballpark plus the free tenant signup link \u2014 the figure is illustrative only, not an approval. Use `estimate_supporter_returns` when a prospective Supporter gives an amount (UGX) to return an illustrative Returns range (simple to compounding, at 15% monthly platform rewards) plus the free Supporter signup link \u2014 an illustration only, not a guarantee. Use `find_available_houses` to return a small read-only sample of available house listings by district/area (public, non-sensitive fields only) plus the free tenant signup link to view details and apply. Personal figures require signing in, so always offer the relevant signup link. All amounts are in UGX.",
  tools: [how_welile_works_default, explore_welile_default, estimate_rent_access_default, estimate_supporter_returns_default, find_available_houses_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_public_default, { functionName: "mcp-public" }));
