import { defineTool } from "@lovable.dev/mcp-js";
import { z } from "zod";
import * as XLSX from "xlsx";
import { buildStatement, statementTitle, supabaseForUser, ugx, type Statement } from "../statement";
import { textPdf } from "../simplePdf";

const BUCKET = "wallet-statements";
const SIGNED_URL_TTL_SECONDS = 60 * 60 * 24 * 7; // 7 days

function pad(value: string, width: number): string {
  const text = value.length > width ? `${value.slice(0, width - 2)}..` : value;
  return text.padEnd(width, " ");
}

function padLeft(value: string, width: number): string {
  return value.length > width ? value.slice(0, width) : value.padStart(width, " ");
}

function pdfBytes(statement: Statement): Uint8Array {
  const lines: string[] = [
    "WELILE RECEIPTS - WALLET STATEMENT",
    statementTitle(statement),
    `Generated: ${new Date().toISOString().slice(0, 16).replace("T", " ")} UTC`,
    "",
    `Money in:    ${ugx(statement.total_in)}`,
    `Money out:   ${ugx(statement.total_out)}`,
    `Net movement:${ugx(statement.net_movement)}`,
    `Withdrawable balance now: ${ugx(statement.closing_withdrawable)}`,
    "",
    `${pad("DATE", 12)}${pad("CATEGORY", 26)}${pad("DIRECTION", 11)}${padLeft("AMOUNT (UGX)", 16)}  DESCRIPTION`,
    "-".repeat(110),
  ];
  for (const r of statement.rows) {
    lines.push(
      `${pad(r.date, 12)}${pad(r.category, 26)}${pad(r.direction, 11)}` +
        `${padLeft(Math.round(r.amount).toLocaleString("en-US"), 16)}  ${r.description.slice(0, 42)}`,
    );
  }
  if (!statement.rows.length) lines.push("No activity in this period.");
  lines.push("", "All amounts in UGX. Statement generated by Welile Receipts.");
  return textPdf(lines);
}

function xlsxBytes(statement: Statement): Uint8Array {
  const book = XLSX.utils.book_new();
  const summary = XLSX.utils.aoa_to_sheet([
    ["Welile Receipts — Wallet statement"],
    ["Period", statementTitle(statement)],
    ["Generated (UTC)", new Date().toISOString()],
    ["Currency", "UGX"],
    [],
    ["Money in", statement.total_in],
    ["Money out", statement.total_out],
    ["Net movement", statement.net_movement],
    ["Withdrawable balance now", statement.closing_withdrawable],
    ["Entries", statement.rows.length],
  ]);
  summary["!cols"] = [{ wch: 26 }, { wch: 42 }];
  XLSX.utils.book_append_sheet(book, summary, "Summary");

  const sheet = XLSX.utils.json_to_sheet(
    statement.rows.map((r) => ({
      Date: r.date,
      Category: r.category,
      Direction: r.direction,
      Bucket: r.bucket,
      "Amount (UGX)": r.amount,
      Description: r.description,
    })),
    { header: ["Date", "Category", "Direction", "Bucket", "Amount (UGX)", "Description"] },
  );
  sheet["!cols"] = [{ wch: 12 }, { wch: 26 }, { wch: 11 }, { wch: 14 }, { wch: 16 }, { wch: 48 }];
  XLSX.utils.book_append_sheet(book, sheet, "Transactions");

  const out = XLSX.write(book, { type: "array", bookType: "xlsx" }) as ArrayBuffer;
  return new Uint8Array(out);
}

function csvBytes(statement: Statement): Uint8Array {
  const cell = (v: string | number) => `"${String(v).replace(/"/g, '""')}"`;
  const rows = [
    ["Date", "Category", "Direction", "Bucket", "Amount (UGX)", "Description"].join(","),
    ...statement.rows.map((r) =>
      [cell(r.date), cell(r.category), cell(r.direction), cell(r.bucket), r.amount, cell(r.description)].join(","),
    ),
  ].join("\n");
  return new TextEncoder().encode(rows);
}

export default defineTool({
  name: "export_my_wallet_statement",
  title: "Export my wallet statement",
  description:
    "Generate the signed-in user's Welile wallet statement as a PDF, Excel (.xlsx) or CSV file and return a private download link valid for 7 days. Optionally limit it to a date range. Amounts are in UGX.",
  inputSchema: {
    format: z.enum(["pdf", "xlsx", "csv"]).describe("File format to generate. Defaults to pdf.").optional(),
    from: z.string().describe("Optional start date, YYYY-MM-DD (inclusive).").optional(),
    to: z.string().describe("Optional end date, YYYY-MM-DD (inclusive).").optional(),
    limit: z
      .number()
      .int()
      .describe("Maximum number of entries to include. Defaults to 200; capped at 1000.")
      .optional(),
  },
  annotations: { readOnlyHint: false, idempotentHint: false, openWorldHint: false },
  handler: async ({ format, from, to, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const fmt = format ?? "pdf";
    try {
      const statement = await buildStatement(ctx, { from, to, limit });
      const file =
        fmt === "xlsx"
          ? {
              bytes: xlsxBytes(statement),
              contentType: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
              ext: "xlsx",
            }
          : fmt === "csv"
            ? { bytes: csvBytes(statement), contentType: "text/csv", ext: "csv" }
            : { bytes: pdfBytes(statement), contentType: "application/pdf", ext: "pdf" };

      const stamp = new Date().toISOString().replace(/[:.]/g, "-");
      const path = `${ctx.getUserId()}/wallet-statement-${stamp}.${file.ext}`;

      const supabase = supabaseForUser(ctx);
      const { error: uploadError } = await supabase.storage
        .from(BUCKET)
        .upload(path, file.bytes, { contentType: file.contentType, upsert: true });
      if (uploadError) return { content: [{ type: "text", text: uploadError.message }], isError: true };

      const { data: signed, error: signError } = await supabase.storage
        .from(BUCKET)
        .createSignedUrl(path, SIGNED_URL_TTL_SECONDS);
      if (signError || !signed?.signedUrl) {
        return {
          content: [{ type: "text", text: signError?.message ?? "Could not create a download link." }],
          isError: true,
        };
      }

      return {
        content: [
          {
            type: "text",
            text:
              `${statementTitle(statement)} exported as ${fmt.toUpperCase()} ` +
              `(${statement.rows.length} entries, net ${ugx(statement.net_movement)}).\n` +
              `Download (private link, expires in 7 days): ${signed.signedUrl}`,
          },
        ],
        structuredContent: {
          format: fmt,
          download_url: signed.signedUrl,
          expires_in_seconds: SIGNED_URL_TTL_SECONDS,
          entries: statement.rows.length,
          total_in: statement.total_in,
          total_out: statement.total_out,
          net_movement: statement.net_movement,
          closing_withdrawable: statement.closing_withdrawable,
          truncated: statement.truncated,
        },
      };
    } catch (e) {
      return { content: [{ type: "text", text: (e as Error).message }], isError: true };
    }
  },
});