// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/get-my-profile.ts
import { createClient } from "npm:@supabase/supabase-js@2.89.0";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
function supabaseForUser(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_my_profile_default = defineTool({
  name: "get_my_profile",
  title: "Get my profile",
  description: "Return the signed-in Welile user's profile: name, phone, verification status, and location.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await supabaseForUser(ctx).from("profiles").select(
      "full_name, phone, email, verified, country, city, district, tenant_status, agent_type, created_at"
    ).eq("id", ctx.getUserId()).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) return { content: [{ type: "text", text: "No profile found for this user." }] };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { profile: data }
    };
  }
});

// src/lib/mcp/tools/get-my-wallet.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@2.89.0";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
function supabaseForUser2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_my_wallet_default = defineTool2({
  name: "get_my_wallet",
  title: "Get my wallet balance",
  description: "Return the signed-in user's Welile wallet: withdrawable balance (the amount they can withdraw) plus float and advance buckets. Amounts are in UGX.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser2(ctx);
    const userId = ctx.getUserId();
    const { data: available, error: rpcError } = await supabase.rpc(
      "get_user_available_balance",
      { p_user_id: userId }
    );
    if (rpcError) return { content: [{ type: "text", text: rpcError.message }], isError: true };
    const { data: wallet } = await supabase.from("wallets").select("float_balance, advance_balance, currency").eq("user_id", userId).maybeSingle();
    const result = {
      currency: "UGX",
      withdrawable_balance: Number(available ?? 0),
      float_balance: Number(wallet?.float_balance ?? 0),
      advance_balance: Number(wallet?.advance_balance ?? 0)
    };
    return {
      content: [
        {
          type: "text",
          text: `Withdrawable: UGX ${result.withdrawable_balance.toLocaleString()} | Float: UGX ${result.float_balance.toLocaleString()} | Advance: UGX ${result.advance_balance.toLocaleString()}`
        }
      ],
      structuredContent: { wallet: result }
    };
  }
});

// src/lib/mcp/tools/list-my-transactions.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@2.89.0";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^4.4.3";
import { applyCustomerWalletLedgerFilters, isCustomerWalletLedgerEntryVisible } from "npm:@/lib/customerWalletHistory";
function supabaseForUser3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_my_transactions_default = defineTool3({
  name: "list_my_transactions",
  title: "List my recent transactions",
  description: "List the signed-in user's most recent wallet ledger entries (deposits, withdrawals, commissions). Amounts are in UGX.",
  inputSchema: {
    limit: z.number().int().describe("How many recent entries to return. Defaults to 20; capped at 100.").optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const take = Math.min(Math.max(limit ?? 20, 1), 100);
    const { data, error } = await applyCustomerWalletLedgerFilters(supabaseForUser3(ctx).from("general_ledger").select("id, created_at, category, direction, amount, description, wallet_bucket, classification, source_table, reference_id").eq("user_id", ctx.getUserId()).eq("ledger_scope", "wallet")).order("created_at", { ascending: false }).limit(take);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const rows = (data ?? []).filter(isCustomerWalletLedgerEntryVisible);
    const summary = rows.map(
      (r) => `${new Date(r.created_at).toISOString().slice(0, 10)} \xB7 ${r.category} \xB7 ${r.direction} UGX ${Number(r.amount).toLocaleString()}`
    ).join("\n");
    return {
      content: [{ type: "text", text: summary || "No transactions found." }],
      structuredContent: { transactions: rows }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "wirntoujqoyjobfhyelc";
var mcp_default = defineMcp({
  name: "welile-mcp",
  title: "Welile Receipts MCP",
  version: "0.1.0",
  instructions: "Tools for a signed-in Welile Receipts user. Use `get_my_profile` for account details, `get_my_wallet` for the UGX wallet balance, and `list_my_transactions` for recent wallet activity. All amounts are in UGX and scoped to the authenticated user.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [get_my_profile_default, get_my_wallet_default, list_my_transactions_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
