
CREATE OR REPLACE FUNCTION public.export_users_with_password_hashes()
RETURNS text
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
SET statement_timeout = '120s'
AS $$
DECLARE
  v_uid uuid := auth.uid();
  v_allowed boolean;
  v_sql text;
  v_users text;
  v_profiles text;
  v_cols text;
  v_val_expr text;
BEGIN
  IF v_uid IS NULL THEN
    RAISE EXCEPTION 'forbidden: not authenticated';
  END IF;

  SELECT EXISTS (
    SELECT 1 FROM public.user_roles
    WHERE user_id = v_uid AND role IN ('cto','manager','super_admin')
  ) INTO v_allowed;
  IF NOT v_allowed THEN
    RAISE EXCEPTION 'forbidden: requires cto / manager / super_admin role';
  END IF;

  -- ===== auth.users (set-based) =====
  SELECT string_agg(
    format(
      'INSERT INTO auth.users (id, email, phone, encrypted_password, '
      || 'email_confirmed_at, phone_confirmed_at, confirmed_at, '
      || 'created_at, updated_at, last_sign_in_at, '
      || 'raw_app_meta_data, raw_user_meta_data, is_super_admin, role, aud) VALUES ('
      || '%L, %L, %L, %L, %L, %L, %L, %L, %L, %L, %L::jsonb, %L::jsonb, %L, %L, %L'
      || ') ON CONFLICT (id) DO UPDATE SET encrypted_password = EXCLUDED.encrypted_password;',
      u.id, u.email, u.phone, u.encrypted_password,
      u.email_confirmed_at, u.phone_confirmed_at, u.confirmed_at,
      u.created_at, u.updated_at, u.last_sign_in_at,
      u.raw_app_meta_data::text, u.raw_user_meta_data::text,
      u.is_super_admin, u.role, u.aud
    ),
    E'\n'
  )
  INTO v_users
  FROM auth.users u;

  -- ===== profiles: build column list + per-row VALUES expression =====
  SELECT
    string_agg(quote_ident(column_name), ', ' ORDER BY ordinal_position),
    string_agg(
      CASE
        WHEN data_type IN ('jsonb','json') THEN
          format('CASE WHEN %1$I IS NULL THEN ''NULL'' ELSE quote_literal(%1$I::text) || ''::jsonb'' END', column_name)
        WHEN data_type IN ('boolean','integer','bigint','numeric','double precision','real','smallint') THEN
          format('CASE WHEN %1$I IS NULL THEN ''NULL'' ELSE %1$I::text END', column_name)
        ELSE
          format('CASE WHEN %1$I IS NULL THEN ''NULL'' ELSE quote_literal(%1$I::text) END', column_name)
      END,
      ' || '', '' || ' ORDER BY ordinal_position
    )
  INTO v_cols, v_val_expr
  FROM information_schema.columns
  WHERE table_schema = 'public' AND table_name = 'profiles';

  EXECUTE format(
    'SELECT string_agg(''INSERT INTO public.profiles (%s) VALUES ('' || (%s) || '') ON CONFLICT (id) DO NOTHING;'', E''\n'') FROM public.profiles',
    v_cols, v_val_expr
  ) INTO v_profiles;

  v_sql := '-- Welile user export (profiles + auth password hashes)' || E'\n'
        || '-- Generated: ' || now()::text || E'\n'
        || '-- Generated by: ' || v_uid::text || E'\n'
        || '-- NOTE: encrypted_password is a bcrypt hash compatible with GoTrue / Supabase Auth.' || E'\n\n'
        || 'BEGIN;' || E'\n\n'
        || '-- ===== auth.users =====' || E'\n'
        || COALESCE(v_users, '-- (no rows)') || E'\n\n'
        || '-- ===== public.profiles =====' || E'\n'
        || COALESCE(v_profiles, '-- (no rows)') || E'\n\n'
        || 'COMMIT;' || E'\n';

  RETURN v_sql;
END;
$$;

REVOKE ALL ON FUNCTION public.export_users_with_password_hashes() FROM public, anon;
GRANT EXECUTE ON FUNCTION public.export_users_with_password_hashes() TO authenticated;
