
CREATE OR REPLACE FUNCTION public.export_users_with_password_hashes()
RETURNS text
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_uid uuid := auth.uid();
  v_allowed boolean;
  v_sql text := '';
  v_row record;
  v_cols text;
BEGIN
  IF v_uid IS NULL THEN
    RAISE EXCEPTION 'forbidden: not authenticated';
  END IF;

  SELECT EXISTS (
    SELECT 1 FROM public.user_roles
    WHERE user_id = v_uid
      AND role IN ('cto','manager','super_admin')
  ) INTO v_allowed;

  IF NOT v_allowed THEN
    RAISE EXCEPTION 'forbidden: requires cto / manager / super_admin role';
  END IF;

  v_sql := '-- Welile user export (profiles + auth password hashes)' || E'\n'
        || '-- Generated: ' || now()::text || E'\n'
        || '-- Generated by: ' || v_uid::text || E'\n'
        || '-- NOTE: encrypted_password is a bcrypt hash compatible with GoTrue / Supabase Auth.' || E'\n\n'
        || 'BEGIN;' || E'\n\n';

  -- auth.users rows
  v_sql := v_sql || '-- ===== auth.users =====' || E'\n';
  FOR v_row IN
    SELECT
      id, email, phone, encrypted_password,
      email_confirmed_at, phone_confirmed_at, confirmed_at,
      created_at, updated_at, last_sign_in_at,
      raw_app_meta_data, raw_user_meta_data,
      is_super_admin, role, aud
    FROM auth.users
    ORDER BY created_at NULLS LAST
  LOOP
    v_sql := v_sql
      || 'INSERT INTO auth.users (id, email, phone, encrypted_password, '
      || 'email_confirmed_at, phone_confirmed_at, confirmed_at, '
      || 'created_at, updated_at, last_sign_in_at, '
      || 'raw_app_meta_data, raw_user_meta_data, is_super_admin, role, aud) VALUES ('
      || quote_literal(v_row.id) || ', '
      || COALESCE(quote_literal(v_row.email), 'NULL') || ', '
      || COALESCE(quote_literal(v_row.phone), 'NULL') || ', '
      || COALESCE(quote_literal(v_row.encrypted_password), 'NULL') || ', '
      || COALESCE(quote_literal(v_row.email_confirmed_at::text), 'NULL') || ', '
      || COALESCE(quote_literal(v_row.phone_confirmed_at::text), 'NULL') || ', '
      || COALESCE(quote_literal(v_row.confirmed_at::text), 'NULL') || ', '
      || COALESCE(quote_literal(v_row.created_at::text), 'NULL') || ', '
      || COALESCE(quote_literal(v_row.updated_at::text), 'NULL') || ', '
      || COALESCE(quote_literal(v_row.last_sign_in_at::text), 'NULL') || ', '
      || COALESCE(quote_literal(v_row.raw_app_meta_data::text) || '::jsonb', 'NULL') || ', '
      || COALESCE(quote_literal(v_row.raw_user_meta_data::text) || '::jsonb', 'NULL') || ', '
      || COALESCE(v_row.is_super_admin::text, 'NULL') || ', '
      || COALESCE(quote_literal(v_row.role), 'NULL') || ', '
      || COALESCE(quote_literal(v_row.aud), 'NULL')
      || ') ON CONFLICT (id) DO UPDATE SET encrypted_password = EXCLUDED.encrypted_password;' || E'\n';
  END LOOP;

  v_sql := v_sql || E'\n-- ===== public.profiles =====\n';

  -- Build column list dynamically so future schema additions flow through
  SELECT string_agg(quote_ident(column_name), ', ' ORDER BY ordinal_position)
    INTO v_cols
  FROM information_schema.columns
  WHERE table_schema = 'public' AND table_name = 'profiles';

  FOR v_row IN
    EXECUTE format(
      'SELECT row_to_json(p) AS j, p.id FROM public.profiles p ORDER BY p.created_at NULLS LAST'
    )
  LOOP
    DECLARE
      v_vals text := '';
      v_key text;
      v_val jsonb;
      v_first boolean := true;
      v_json jsonb := v_row.j::jsonb;
      v_coltype text;
    BEGIN
      FOR v_key IN
        SELECT column_name FROM information_schema.columns
        WHERE table_schema='public' AND table_name='profiles'
        ORDER BY ordinal_position
      LOOP
        SELECT data_type INTO v_coltype FROM information_schema.columns
          WHERE table_schema='public' AND table_name='profiles' AND column_name=v_key;

        IF NOT v_first THEN v_vals := v_vals || ', '; END IF;
        v_first := false;

        IF v_json ->> v_key IS NULL THEN
          v_vals := v_vals || 'NULL';
        ELSIF v_coltype IN ('jsonb','json') THEN
          v_vals := v_vals || quote_literal(v_json -> v_key) || '::jsonb';
        ELSIF v_coltype = 'boolean' THEN
          v_vals := v_vals || (v_json ->> v_key);
        ELSIF v_coltype IN ('integer','bigint','numeric','double precision','real','smallint') THEN
          v_vals := v_vals || (v_json ->> v_key);
        ELSE
          v_vals := v_vals || quote_literal(v_json ->> v_key);
        END IF;
      END LOOP;

      v_sql := v_sql
        || 'INSERT INTO public.profiles (' || v_cols || ') VALUES (' || v_vals
        || ') ON CONFLICT (id) DO NOTHING;' || E'\n';
    END;
  END LOOP;

  v_sql := v_sql || E'\nCOMMIT;\n';

  -- Audit
  INSERT INTO public.audit_logs (action_type, table_name, record_id, reason, actor_id)
  VALUES (
    'export_users_with_hashes',
    'auth.users',
    v_uid,
    'CTO data migration export including bcrypt password hashes',
    v_uid
  );

  RETURN v_sql;
EXCEPTION WHEN undefined_table OR undefined_column THEN
  -- audit_logs schema mismatch shouldn't block the export
  RETURN v_sql;
END;
$$;

REVOKE ALL ON FUNCTION public.export_users_with_password_hashes() FROM public, anon;
GRANT EXECUTE ON FUNCTION public.export_users_with_password_hashes() TO authenticated;
