import { useMemo, useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import { useNavigate } from 'react-router-dom';
import { supabase } from '@/integrations/supabase/client';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { ScrollArea } from '@/components/ui/scroll-area';
import { Popover, PopoverContent, PopoverTrigger } from '@/components/ui/popover';
import { Checkbox } from '@/components/ui/checkbox';
import { ArrowLeft, ClipboardList, Filter, Loader2, X, Download } from 'lucide-react';
import { format, formatDistanceToNow } from 'date-fns';
import { downloadCsv, csvTimestamp } from '@/lib/csvExport';

interface AuditRow {
  id: string;
  generated_for: string | null;
  generated_by: string | null;
  tier: string | null;
  response_rate: number | null;
  reason_codes: string[] | null;
  reasons: any;
  context: any;
  generated_at: string;
  agent_name?: string;
  generator_name?: string;
}

const TIER_COLOR: Record<string, string> = {
  emerald: 'bg-emerald-500/10 text-emerald-600',
  amber: 'bg-amber-500/10 text-amber-600',
  orange: 'bg-orange-500/10 text-orange-600',
  destructive: 'bg-destructive/10 text-destructive',
  violet: 'bg-violet-500/10 text-violet-600',
};

export default function AgentRecommendationAudit() {
  const navigate = useNavigate();
  const [dateFrom, setDateFrom] = useState('');
  const [dateTo, setDateTo] = useState('');
  const [agentSearch, setAgentSearch] = useState('');
  const [selectedCodes, setSelectedCodes] = useState<string[]>([]);

  const { data: rows = [], isLoading } = useQuery({
    queryKey: ['agent-recommendation-audit', dateFrom, dateTo],
    queryFn: async () => {
      let query = supabase
        .from('agent_recommendation_audit')
        .select('*')
        .order('generated_at', { ascending: false })
        .limit(500);

      if (dateFrom) query = query.gte('generated_at', new Date(dateFrom).toISOString());
      if (dateTo) {
        const end = new Date(dateTo);
        end.setHours(23, 59, 59, 999);
        query = query.lte('generated_at', end.toISOString());
      }

      const { data, error } = await query;
      if (error) throw error;
      const list = (data || []) as AuditRow[];

      // Resolve names
      const ids = [
        ...new Set(
          list.flatMap((r) => [r.generated_for, r.generated_by]).filter(Boolean) as string[],
        ),
      ];
      const nameMap = new Map<string, string>();
      if (ids.length) {
        const { data: profiles } = await supabase
          .from('profiles')
          .select('id, full_name')
          .in('id', ids);
        profiles?.forEach((p) => nameMap.set(p.id, p.full_name || 'Unknown'));
      }
      return list.map((r) => ({
        ...r,
        agent_name: r.generated_for ? nameMap.get(r.generated_for) || 'Unknown' : '—',
        generator_name: r.generated_by ? nameMap.get(r.generated_by) || 'Unknown' : 'System',
      }));
    },
    staleTime: 30000,
  });

  const allCodes = useMemo(() => {
    const set = new Set<string>();
    rows.forEach((r) => r.reason_codes?.forEach((c) => set.add(c)));
    return [...set].sort();
  }, [rows]);

  const filtered = useMemo(() => {
    const search = agentSearch.trim().toLowerCase();
    return rows.filter((r) => {
      if (search) {
        const hay = `${r.agent_name} ${r.generated_for} ${r.generator_name}`.toLowerCase();
        if (!hay.includes(search)) return false;
      }
      if (selectedCodes.length) {
        if (!r.reason_codes?.some((c) => selectedCodes.includes(c))) return false;
      }
      return true;
    });
  }, [rows, agentSearch, selectedCodes]);

  const toggleCode = (code: string) =>
    setSelectedCodes((prev) =>
      prev.includes(code) ? prev.filter((c) => c !== code) : [...prev, code],
    );

  const clearFilters = () => {
    setDateFrom('');
    setDateTo('');
    setAgentSearch('');
    setSelectedCodes([]);
  };

  const hasFilters = dateFrom || dateTo || agentSearch || selectedCodes.length > 0;

  const handleExport = () => {
    downloadCsv(
      `agent-recommendation-audit-${format(new Date(), 'yyyy-MM-dd')}.csv`,
      ['Generated at', 'Agent', 'Generated by', 'Tier', 'Response rate', 'Reason codes', 'Summaries'],
      filtered.map((r) => [
        csvTimestamp(r.generated_at),
        r.agent_name,
        r.generator_name,
        r.tier || '',
        r.response_rate != null ? `${r.response_rate}%` : '',
        (r.reason_codes || []).join('; '),
        Array.isArray(r.reasons)
          ? r.reasons.map((x: any) => x?.summary).filter(Boolean).join(' | ')
          : '',
      ]),
    );
  };

  return (
    <div className="min-h-screen bg-background pb-20">
      <div className="sticky top-0 z-40 bg-background/95 backdrop-blur-lg border-b">
        <div className="flex items-center gap-3 p-4">
          <Button variant="ghost" size="icon" onClick={() => navigate(-1)} className="h-10 w-10">
            <ArrowLeft className="h-5 w-5" />
          </Button>
          <div className="flex-1">
            <h1 className="text-lg font-bold flex items-center gap-2">
              <ClipboardList className="h-5 w-5 text-primary" />
              Recommendation Audit
            </h1>
            <p className="text-xs text-muted-foreground">
              When & why 7-day improvement recommendations were generated
            </p>
          </div>
        </div>
      </div>

      <div className="p-4 space-y-4">
        <Card>
          <CardHeader className="pb-3">
            <CardTitle className="text-sm flex items-center gap-2">
              <Filter className="h-4 w-4 text-primary" /> Filters
            </CardTitle>
          </CardHeader>
          <CardContent className="space-y-4">
            <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-3">
              <div className="space-y-1.5">
                <Label className="text-xs">From date</Label>
                <Input type="date" value={dateFrom} onChange={(e) => setDateFrom(e.target.value)} className="h-10" />
              </div>
              <div className="space-y-1.5">
                <Label className="text-xs">To date</Label>
                <Input type="date" value={dateTo} onChange={(e) => setDateTo(e.target.value)} className="h-10" />
              </div>
              <div className="space-y-1.5">
                <Label className="text-xs">Agent (name or ID)</Label>
                <Input
                  placeholder="Search agent…"
                  value={agentSearch}
                  onChange={(e) => setAgentSearch(e.target.value)}
                  className="h-10"
                />
              </div>
              <div className="space-y-1.5">
                <Label className="text-xs">Reason codes</Label>
                <Popover>
                  <PopoverTrigger asChild>
                    <Button variant="outline" className="h-10 w-full justify-start font-normal">
                      {selectedCodes.length ? `${selectedCodes.length} selected` : 'Any reason'}
                    </Button>
                  </PopoverTrigger>
                  <PopoverContent className="w-64 p-2" align="start">
                    <ScrollArea className="max-h-64">
                      {allCodes.length === 0 ? (
                        <p className="text-xs text-muted-foreground p-2">No reason codes yet</p>
                      ) : (
                        <div className="space-y-1">
                          {allCodes.map((code) => (
                            <label
                              key={code}
                              className="flex items-center gap-2 rounded-md px-2 py-1.5 hover:bg-muted/50 cursor-pointer text-sm"
                            >
                              <Checkbox
                                checked={selectedCodes.includes(code)}
                                onCheckedChange={() => toggleCode(code)}
                              />
                              <span className="font-mono text-xs">{code}</span>
                            </label>
                          ))}
                        </div>
                      )}
                    </ScrollArea>
                  </PopoverContent>
                </Popover>
              </div>
            </div>
            <div className="flex flex-wrap items-center gap-2">
              {selectedCodes.map((code) => (
                <Badge key={code} variant="secondary" className="gap-1 font-mono text-[10px]">
                  {code}
                  <button onClick={() => toggleCode(code)}>
                    <X className="h-3 w-3" />
                  </button>
                </Badge>
              ))}
              {hasFilters && (
                <Button variant="ghost" size="sm" onClick={clearFilters} className="h-7 text-xs">
                  Clear filters
                </Button>
              )}
              <div className="ml-auto flex items-center gap-2">
                <span className="text-xs text-muted-foreground">{filtered.length} record(s)</span>
                <Button
                  variant="outline"
                  size="sm"
                  onClick={handleExport}
                  disabled={!filtered.length}
                  className="h-7 gap-1.5 text-xs"
                >
                  <Download className="h-3.5 w-3.5" /> Export
                </Button>
              </div>
            </div>
          </CardContent>
        </Card>

        <Card>
          <CardContent className="p-0">
            {isLoading ? (
              <div className="flex justify-center py-16">
                <Loader2 className="h-6 w-6 animate-spin text-primary" />
              </div>
            ) : filtered.length === 0 ? (
              <div className="py-16 text-center text-sm text-muted-foreground">
                No recommendation audit records match your filters
              </div>
            ) : (
              <ScrollArea className="max-h-[60vh]">
                <div className="divide-y">
                  {filtered.map((r) => {
                    const tone = r.context?.tier_tone as string | undefined;
                    const color = (tone && TIER_COLOR[tone]) || 'bg-muted text-muted-foreground';
                    const reasons = Array.isArray(r.reasons) ? r.reasons : [];
                    return (
                      <div key={r.id} className="p-3.5 space-y-2 hover:bg-muted/20 transition-colors">
                        <div className="flex items-start justify-between gap-3">
                          <div className="min-w-0">
                            <p className="text-sm font-medium truncate">{r.agent_name}</p>
                            <p className="text-[11px] text-muted-foreground">
                              by {r.generator_name}
                            </p>
                          </div>
                          <div className="text-right shrink-0">
                            <div className="flex items-center gap-1.5 justify-end">
                              {r.tier && (
                                <Badge className={`text-[10px] px-1.5 py-0 border-0 ${color}`}>
                                  {r.tier}
                                </Badge>
                              )}
                              {r.response_rate != null && (
                                <span className="text-xs font-semibold">{r.response_rate}%</span>
                              )}
                            </div>
                            <p className="text-[11px] text-muted-foreground">
                              {formatDistanceToNow(new Date(r.generated_at), { addSuffix: true })}
                            </p>
                            <p className="text-[10px] text-muted-foreground/60">
                              {format(new Date(r.generated_at), 'dd MMM yyyy, HH:mm')}
                            </p>
                          </div>
                        </div>
                        {(r.reason_codes?.length ?? 0) > 0 && (
                          <div className="flex flex-wrap gap-1">
                            {r.reason_codes!.map((c) => (
                              <Badge key={c} variant="outline" className="font-mono text-[10px] px-1.5 py-0">
                                {c}
                              </Badge>
                            ))}
                          </div>
                        )}
                        {reasons.length > 0 && (
                          <ul className="space-y-0.5 pl-1">
                            {reasons.map((rec: any, i: number) => (
                              <li key={i} className="text-[11px] text-muted-foreground leading-snug">
                                • {rec?.summary || rec?.code}
                              </li>
                            ))}
                          </ul>
                        )}
                      </div>
                    );
                  })}
                </div>
              </ScrollArea>
            )}
          </CardContent>
        </Card>
      </div>
    </div>
  );
}